import { talentTypes } from "~~/server/database/schema";

export default async function seedTalents(db: any) {
    const talents = [
      {
        name: "Endure",
        description: `Until the warriors next turn, they gain (TGH \\2) Deflection and (10 + level \\6) temporary Wounds`,
        groupId: 29,
        talentTypeId: 1,
        createdAt: new Date(),
      },
      {
        name: "Reckless Strike",
        description: `The warrior's next melee attack agains +(5 x STR)% armour penetration and (2x Strength) damage and ignores (3x WS)% of the target's parry. Every enemy who survives an attack enhanced by this ability will attawck the warrior in return, including creatures with ranged weapons.`,
        groupId: 29,
        talentTypeId: 1,
        createdAt: new Date(),
      },
      {
        name: "Sworn Enemy",
        description: `The Warrior marks a target, gaining +(10 + 2 x TGH bonus)% armour and +(2 + STR bonus) damage on melee attacks against that target.
If the target attacks the Warrior during this round, the Warrior gains +1 AP (once per round).`,
        groupId: 29,
        talentTypeId: 1,
        createdAt: new Date(),
      },
      {
        name: "Break Through",
        description: ` `,
        groupId: 29,
        talentTypeId: 1,
        createdAt: new Date(),
      },
      {
        name: "Forceful Strike",
        description: `The Warrior gathers all their strength for a crushing strike. Their next melee attack pushes the enemy away. The distance of that push is equal to (1 + Strength bonus / 2) cells.`,
        groupId: 29,
        talentTypeId: 1,
        createdAt: new Date(),
      },
      {
        name: "Taunting Scream",
        description: `The Warrior screams at their enemies to draw their attention and becomes a priority target of any enemy who fails a Willpower resistance test.`,
        groupId: 29,
        talentTypeId: 1,
        createdAt: new Date(),
      },

      {
        name: "Daring Breach",
        description: ``,
        groupId: 29,
        talentTypeId: 5,
        createdAt: new Date(),
      },

      {
        name: "Daring Breach I",
        description: ``,
        groupId: 29,
        talentTypeId: 5,
        createdAt: new Date(),
      },

      {
        name: "Daring Breach II",
        description: ``,
        groupId: 29,
        talentTypeId: 5,
        createdAt: new Date(),
      },

      {
        name: "Daring Breach III",
        description: ``,
        groupId: 29,
        talentTypeId: 5,
        createdAt: new Date(),
      },

      {
        name: "Daring Breach IV",
        description: ``,
        groupId: 29,
        talentTypeId: 5,
        createdAt: new Date(),
      },

      // Officer Talents

      {
        name: "Voice of Command",
        description: `The Officer forces an ally to fully push themselves, increasing their characteristics by +(5 + 2 x Officer's FEL bonus) for 1 round. Additionally, all of the Officer's abilities can be applied to the target of Voice of Command from any distance. A character who becomes the target of Voice of Command cannot be targeted by this ability again for the next 2 rounds.`,
        groupId: 30,
        talentTypeId: 1,
        createdAt: new Date(),
      },
      {
        name: "Air of Authority",
        description: `The Officer increases an ally's Resolve by a Resolve until the end of combat.
If the target is under the effect of Voice of Command, they will start their next turn with 1 additional action point.`,
        groupId: 30,
        talentTypeId: 1,
        createdAt: new Date(),
      },
      {
        name: "Get back in the fight!",
        description: `The Officer encourages a target ally to immediately recover from burning, bleeding, toxin and stun effects.
If the target is under Voice of Command effect, it gains +2×(Officer's WP bonus) temporary Wounds.`,
        groupId: 30,
        talentTypeId: 1,
        createdAt: new Date(),
      },
      {
        name: "Break Their Ranks!",
        description: `This ability can only target allies who have enemies adjacent to them.
Until the start of the Officer's next turn all melee attacks made by the target deal additional damage equal to (Officer's FEL bonus/ 2) multiplied by the number of enemies adjacent to the target when this ability is used.
If the target is under the effect of Voice of Command, they immediately make an attack of opportunity against an adjacent enemy, targeting the one with the lowest remaining wounds.`,
        groupId: 30,
        talentTypeId: 1,
        createdAt: new Date(),
      },
      {
        name: "Move, Move, Move!",
        description: `The Officer immediately grants an ally additional Movement points equal to FEL bonus.
If the target is under the effect of Voice of Command, it ignores attacks of opportunity until the end of the Officer's turn.`,
        groupId: 30,
        talentTypeId: 1,
        createdAt: new Date(),
      },

      {
        name: "Take Aim!",
        description: `The target's next attack will ignore cover and will
If the target is under the effect of voice of command, this attack will ignore enemy dodge. Additionally, the damage from this attack can't be reduced below (30 + 3 x FEL bonus)% for any reason.`,
        groupId: 30,
        talentTypeId: 1,
        createdAt: new Date(),
      },

      // Operative Talents
      {
        name: "Analyse Enemies",
        description: `The Operative targets one enemy within line of sight. That target immediately gains +(1 + INT bonus / 2) exploits.
Expose Weakness: The Operative removes all exploits from the target to decrease the target's dodge, parry, and armour by -(15 + exploits stacks x PER bonus)% until the start of the Operative's next turn.
If this ability reduces the target's armour to 0, the Operative only removes only half of the exploits from the target.`,
        groupId: 31,
        talentTypeId: 1,
        createdAt: new Date(),
      },
      {
        name: "Joint Analysis	",
        description: `Until the Operative's next turn, their allies' attacks also remove exploits and deal +INT bonus more damage.`,
        groupId: 31,
        talentTypeId: 1,
        createdAt: new Date(),
      },
      {
        name: "Precise Attack	",
        description: `For the next attack against a target affected by an exploit, that target's cover fficiency will be reduced by -(15 + (PER bonus/3 x stacks of exploit))%. This attack will have +(15 + PER bonus/3- x stacks of exploit)% hit chance.
`,
        groupId: 31,
        talentTypeId: 1,
        createdAt: new Date(),
      },
      {
        name: "Intimidation",
        description: `The Operative's next non-area attack inflicts the intimidated effect on the first target hit by the attack and all enemies in a 5-cell radius around that target.
The damage dealt by intimidated enemies is reduced by -(5 + PER bonus/2)% until the Operative's next turn. This negative effect is doubled for enemies with less than (3 x INT bonus)% armour.`,
        groupId: 31,
        talentTypeId: 1,
        createdAt: new Date(),
      },
      {
        name: "Perfect Spot",
        description: `While in cover, the Operative gains +25% cover efficiency, +15 Perception, and +15 Ballistic Skill. This effect lasts until the Operative moves. Does not stack.
`,
        groupId: 31,
        talentTypeId: 1,
        createdAt: new Date(),
      },
      {
        name: "Tactical Knowledge",
        description: `he Operative removes -1 exploit from each enemy in a 5-cell radius around a point within 10 cells from the Operative. If there is only one enemy in the area, the Operative removes all exploit stacks from that enemy.
All allies gain +(number of removed exploits)% armour until the end of combat. If 4 or more exploits are removed, the Operative gains +(2 x number of removed exploits)% damage until the end of combat.`,
        groupId: 31,
        talentTypeId: 1,
        createdAt: new Date(),
      },

      // Soldier Talents
      {
        name: "Run and Gun",
        description: `The Soldier gains +(2 + AGI bonus / 2) MP. Their next attack costs -1 AP less and does not count toward the attack limit per turn.
Until the end of the next turn, the Soldier becomes winded. While winded, the Soldier suffers a -10 penalty to Skill and cannot use Run and Gun.`,
        groupId: 32,
        talentTypeId: 1,
        createdAt: new Date(),
      },

      {
        name: "Controlled Shot",
        description: `The Soldier gives a sign that they are about to open fire. The Soldier and their allies will automatically dodge the Soldier's next attack.`,
        groupId: 32,
        talentTypeId: 1,
        createdAt: new Date(),
      },
      {
        name: "Dash",
        description: `The Soldier immediately dashes in the selected direction, spending all their Movement points. Does not provoke attacks of opportunity. Allows the Soldier to dash through allies and enemies but not through obstacles.
Can only be used once per round.`,
        groupId: 32,
        talentTypeId: 1,
        createdAt: new Date(),
      },
      {
        name: "Concentrated Fire",
        description: `	The next ranged area attack made by the Soldier deals +((50 + 10 x BS bonus) / number of enemies in the area of effect)% damage and has an additional +(10 + 2 x BS bonus)% dodge reduction.`,
        groupId: 32,
        talentTypeId: 1,
        createdAt: new Date(),
      },
      {
        name: "Entrench",
        description: `The Soldier immediately spends all their AP and MP and gains a +30% bonus to cover efficiency.
The next time the Soldier uses Run and Gun, they gain back all spent AP and MP plus 1 additional AP. It also resets the 7 cooldown of all other Soldier's abilities except for Run and Gun.`,
        groupId: 32,
        talentTypeId: 1,
        createdAt: new Date(),
      },
      {
        name: "Rapid Fire",
        description: `The Soldier's next burst attacks will have its rate of fire doubled but deal -25% less damage. All the shots will follow random trajectories.
Only works with weapons capable of burst fire.`,
        groupId: 32,
        talentTypeId: 1,
        createdAt: new Date(),
      },


      // Bladedancer

      // Common Talents
      ...['Athletics', 'Awareness', 'Carouse', 'Coercion', 'Commerce', 'Demolition', 'Logic', 'Imperium', 'Warp', 'Xenos', 'Medicae', 'Persuasion', 'Tech-Use'].map(skill => ({
        name: `Advanced Skill: ${skill}`,
        description: `Character gains +13 to skill and can re-roll failed skill tests +1`,
        groupId: 34,
        talentTypeId: 4,
        createdAt: new Date(),
      })),
      ...['Athletics', 'Awareness', 'Carouse', 'Coercion', 'Commerce', 'Demolition', 'Logic', 'Imperium', 'Warp', 'Xenos', 'Medicae', 'Persuasion', 'Tech-Use'].map(skill => ({
        name: `Base Skill: ${skill}`,
        description: `Character gains +7 to skill and can improve the skill even if their archetype or origin does not allow it`,
        groupId: 34,
        talentTypeId: 4,
        createdAt: new Date(),
      })),
      ...['Agility','Ballistic Skill', 'Weapon Skill', 'Fellowship', 'Intelligence', 'Perception', 'Toughness', 'Strength', 'Willpower'].map(skill => ({
        name: `Characteristic Training: ${skill}`,
        description: `Character gains +5 to characteristic. The character may improve any trained characteristic even if their archetype or origin does not allow it`,
        groupId: 34,
        talentTypeId: 5,
        createdAt: new Date(),
      })),
     ...['Agility','Ballistic Skill', 'Weapon Skill', 'Fellowship', 'Intelligence', 'Perception', 'Toughness', 'Strength', 'Willpower'].map(skill => ({
        name: `${skill}`,
        description: ``,
        groupId: 34,
        talentTypeId: 6,
        createdAt: new Date(),
      })),

      // Death World Talents
      {
        name: "Death World",
        description: "Once per combat, when the wounds of a death world character drop below 30%, they gain +20% of their maximum wounds as temporary wounds. Death world characters also gain a +20% bonus to dodge and armour while they have at least 1 temporary wound from any a source.",
        groupId: 28,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Brutal Hunter",
        description: "Death world characters gain +15% critical hit chance against targets with the bleeding effect or with 50% or less of their maximum wounds",
        groupId: 28,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Trusty Weapons",
        description: "Death world characters gain +10% to critical hit chance for axes, hammers, and las weapons.",
        groupId: 28,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Wounded Beast",
        description: "Every Injury increases the death world character's Agility and Willpower by +5. Every trauma counts as 3 Injuries.",
        groupId: 28,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Lifetime of scars",
        description: "Death World characters take TGH bonus less damage from flame, toxic damage, and bleeding effects.",
        groupId: 28,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Tenacity",
        description: "Once per combat, when a death world character is suffering from the stunned, blinded, or immobilised condition, this condition is ignored, and they instead gain +20% temporary wounds to their maximum wounds.",
        groupId: 28,
        talentTypeId: 2,
        createdAt: new Date(),
      },

      // Voidborn Talents
      {
        name: "Voidborn",
        description: `A voidborn character can reroll any failed attack, dodge, parry, characteristic, or skill test with a 20% chance of success. This chance cannot be greater than the base success chance of the roll.
Additionally, any enemy dodge or parry against a voidborn character has a 20% chance to fail after a successful roll.`,
        groupId: 22,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Bloody Mess",
        description: `Any time a voidborn character scores a critical hit, there is a 10% chance to double the damage.`,
        groupId: 22,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Contagious Luck",
        description: `Using a non-damaging ability on an ally grants that ally the ability to reroll any failed attack, dodge, parry, characteristic, or skill test with a 20% chance of success for 1 round. This chance cannot be greater than the base success chance of
the roll. Using a non-damaging ability on an enemy grants them a 20% chance to fail a successful dodge or parry test against any character for 1 round.`,
        groupId: 22,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Just a flesh wound",
        description: `The voidborn character has a 20% chance to survive after suffering lethal damage, surviving with 1 wound.`,
        groupId: 22,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Jinx",
        description: `While a voidborn character has more than 50% wounds, all chances of all creatures (including enemies) in a 3-cell radius are increased by +10%. While a voidborn character has less than 50% wounds, all chances of all creatures
(including enemies) in a 3-cell radius are decreased by -10%.`,
        groupId: 22,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Be Smart	",
        description: `Any time an ability or talent uses the Fellowship bonus, a voidborn character can instead use the Intelligence bonus, if it is higher. Additionally, voidborn characters can always upgrade Intelligence even if their archetype does not allow it.
`,
        groupId: 22,
        talentTypeId: 2,
        createdAt: new Date(),
      },
 {
        name: "Hive World",
        description: `Hive world characters gain +((1 + FEL bonus) / 2) resolve if there are 3 or more creatures (allies or enemies) in a 3-cell radius. They suffer a -2 penalty to resolve with no creatures around.`,
        groupId: 21,
        talentTypeId: 3,
        createdAt: new Date(),
      },
      {
        name: "Comradery",
        description: `Hive world characters can pass Willpower resistance tests using their Fellowship value instead, if the character's Fellowship is higher.`,
        groupId: 21,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Outnumber",
        description: `If a hive world character has melee superiority against the enemy, the effect is increased by +10. If an enemy has melee superiority against a hive world character, the effect is decreased by -10. Melee Superiority: in melee combat, any target surrounded by more allies than enemies receives a +10 WS bonus for each additional ally.`,
        groupId: 22,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Weapon Personalisation",
        description: `All ranged weapons dealing physical damage have +1 damage, +5% armour penetration, +1 rate of fire, and -5 to recoil.`,
        groupId: 21,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Helping Hand",
        description: `If a hive world character starts their turn adjacent to an ally, that hive world character gains +2 MP. If they end their turn adjacent to allies, those allies gain +2 MP on their next turn.`,
        groupId: 21,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Fresh Start",
        description: `Hive world characters gain a +50% bonus to dodge against the first attack of opportunity every round.`,
        groupId: 21,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Forge World",
        description: `Choose one: Subskin Armour, grants 5 + (2 x TGH)% armour — Locomotion System, grants AGI/2 MP and 2 x AGI% dodge — Analytics System, grants 10 + INT% critical hit chance.`,
        groupId: 19,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Pinnacle of Weaponry",
        description: `The first attack in combat with any plasma, melta, or power weapon deals additional damage equal to INT bonus. For the remainder of combat, the bonus damage is decreased to (INT bonus / 2).`,
        groupId: 19,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Fires of the Forge",
        description: `Forge world characters gain +TGH bonus deflection against burning effects and flame weapons.`,
        groupId: 19,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Steel of the Forge",
        description: `While wearing heavy armour, forge world characters gain +1 MP, +1 deflection, and cannot fall prone.`,
        groupId: 19,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Persistence of the Forge",
        description: `Forge world characters gain a stacking +10% bonus to hit chance and dodge reduction against any target they hit with a single-target attack. Successful critical hits from single-target attacks increase the hit chance and dodge reduction by +20%.`,
        groupId: 19,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Calculated Relation",
        description: `Forge world characters can use Persuasion, Coercion, and Commerce based on Intelligence instead of Fellowship.`,
        groupId: 18,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Imperial World",
        description: `Imperial world characters can select any characteristic (except Weapon Skill or Ballistic Skill) and add a +10 bonus.`,
        groupId: 18,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Ready to Serve",
        description: `When an Imperial world character is affected by an ally's non-damaging ability or affects an ally with such an ability, their resolve is increased by (FEL bonus / 2) for 1 round.`,
        groupId: 18,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Better to die for the Emperor",
        description: `While under 40% wounds, Imperial world characters gain a +10 bonus to all characteristics and +2 to resolve.`,
        groupId: 18,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Doing My Part",
        description: `If no other character in the current party is from an Imperial world, the first use of any of the character's archetype abilities costs -1 AP less.`,
        groupId: 18,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Know No Heresy",
        description: `Imperial world characters gain +10% critical hit chance and +10% armour against xenos or daemonic creatures. Their allies gain half the bonuses. However, Imperial world characters' Lore (Xenos) and Lore (Warp) are always 0.`,
        groupId: 18,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Stronger Together",
        description: `All allies, excluding xenos, in the current party gain +5 to the same characteristic as was chosen for Humanity's Finest.`,
        groupId: 18,
        talentTypeId: 2,
        createdAt: new Date(),
      },
{
        name: "Fortress World",
        description: `Each time a fortress world character kills an enemy, they gain +10 stacks of never stop shooting. At the start of their turn, there is a (stacks of never stop shooting)% chance that the first attack this round will cost 0 AP and will not
count toward the attack limit per round. If this effect triggers, all the stacks are lost.`,
        groupId: 20,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Combat Addict",
        description: `Fortress world characters gain +7 to Ballistic Skill, Perception, and Willpower while in combat. Yet while out of combat, their Intelligence, Fellowship, Perception, and Willpower are decreased by -7.`,
        groupId: 20,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Hail of Steel",
        description: `Each round fortress world characters gain a stacking +1% bonus to dodge against ranged attacks for each shot they made during this round. Also, the burst attack grants an additional +10 stacks of never stop shooting.`,
        groupId: 20,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Familiar Kickback",
        description: `At the end of their turn, fortress world characters gain stacks of never stop shooting equal to (half the minimal damage of the most damaging ranged weapon they used this round).`,
        groupId: 20,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Spare Magazine",
        description: `Fortress world characters' first reload in combat costs 0 AP. Reloading a weapon grants an additional +10 stacks of never stop shooting.`,
        groupId: 20,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Never Stop Believing",
        description: `When all stacks of never stop shooting should be lost, they become (WP / 2) number of stacks instead. Additionally, a fortress world character may upgrade their Willpower characteristic even if their
current archetypes do not allow it.`,
        groupId: 20,
        talentTypeId: 2,
        createdAt: new Date(),
      },

      {
        name: "Astra Militarum Commander",
        description: `When used for 1 round the commander and their allies do not suffer damage from allied attacks and deal (20+2xFEL)% more damage to enemies that were attacked by them since this ability activation. The effect does not stack. Can only be used once per combat.`,
        groupId: 22,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Suppression Fire!",
        description: `Whilst Regimental Tactics effect lasts, the commander and their allies' weapon attacks gain +20% dodge reduction, parry reduction, block reduction and cover penetration against targets that have been attacked by allies this combat.`,
        groupId: 22,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Field of Fire",
        description: `While the Astra Militarum commander is under the Regimental Tactics effect, all their allies gain +5% to rate of fire for every attack they have made since the start of this effect.`,
        groupId: 22,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Fix Bayonets!",
        description: `Two-handed las weapons equipped by the commander or allies gain a bayonet strike single melee attack that costs 1 AP. This attack deals the same damage as the las weapon and does not count to attack limit.`,
        groupId: 22,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Unflinching Heroism",
        description: `Whenever the commander or their allies performs a heroic act, all the commander's characteristics are increased by +7 until the end of combat.`,
        groupId: 22,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Trench Warfare",
        description: `While the commander is in partial cover, their las weapon's rate of fire is increased by 20% and 40% when in full cover.`,
        groupId: 22,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Commissar",
        description: `Commissar shoots an allied character with the pistol in their primary hand, dealing 100+Coercion% of weapon damage. This shot ignores armour and deflection. Always hits. Ally gains At All Costs effect; if the ally falls unconscious the effect is applied to all other allies besides the commissar. Grants (2xFEL)% damage, (2xFEL)% dodge and parry and (Commissar's Coercion / 10) to all characteristics. Iconic Sidearm: Shots with pistol in primary hand deal (2x Commissar's BS bonus)% more damage, gain 15% critical hit chance, and (2x Commissar FEL bonus)% dodge reduction.`,
        groupId: 22,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "One for the enemies, two for the traitors",
        description: `The effect of the iconic sidearm is now active when a pistol is equipped in either hand (shots with pistol in their primary hand deal FEL% more damage, gain 15% critical chance and dodge reduction).`,
        groupId: 22,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Let them know fear!",
        description: `While the Commissar is adjacent to an enemy, all their allies gain +(1 + Commissar's FEL bonus / 2) resolve; if there are no creatures in a 2-cell radius the commissar gains this bonus resolve.`,
        groupId: 22,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Motivation",
        description: `The commissar's MP is increased by (1 + character level \\ 10). All allies starting their turn in a 2-cell radius around the commissar also gain (1 + character level \\ 10) MP. Once per round, after the commissar performs an attack with a pistol, they gain (FEL \\ 2) MP. Does not stack.`,
        groupId: 22,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Summary Execution",
        description: `When the commissar uses At All Costs! while shooting from behind, the bonuses granted by the effect are doubled.`,
        groupId: 22,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "For the emperor!",
        description: `If an ally remains in combat after being attacked with the ability At All Costs and then kills an enemy while under the effect, they will regain 30% of the wounds lost due to At All Costs as temporary wounds.`,
        groupId: 22,
        talentTypeId: 2,
        createdAt: new Date(),
      },

      {
        name: "Crime Lord",
        description: `At the start of combat, the crime lord gains +INT bonus stacks of the Sure-Fire Plan effect. Activation of this ability consumes 1 stack and makes the next action stronger depending on the type of action: if the crime lord attacks, they deal +(10 + PER bonus)% more damage; if they move, they gain +(10 + PER bonus)% dodge and parry until the start of their next turn; if they use a non-damaging ability on an enemy, that enemy suffers a -(10 + INT bonus)% penalty to damage for one round. Can be used multiple times per turn.`,
        groupId: 22,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Killing Plan",
        description: `The bonus damage of Sure-Fire Plan is increased by +(2 x WS bonus)%. Killing at least one enemy with an attack restores 1 stack of Sure-Fire Plan.`,
        groupId: 22,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Escape Plan",
        description: `The bonus to dodge and parry from Sure-Fire Plan are increased by +(2 x AGI bonus)%. Dodging or parrying at least one attack by the start of the next round restores 1 stack of Sure-Fire Plan.`,
        groupId: 22,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Disorienting Plan",
        description: `An enemy affected by Sure-Fire Plan also suffers a -(10 + 2 x PER bonus)% penalty to dodge and parry.`,
        groupId: 22,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Contingency Plan",
        description: `If at the start of a turn the crime lord has no stacks of Sure-Fire Plan, they gain +1 stack.`,
        groupId: 22,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "The Last Plan",
        description: `Once per combat, if the crime lord has at least 1 stack of Sure-Fire Plan, they do not die from lethal damage. Instead, they heal (5 x Sure-Fire Plan stacks)% of maximum wounds, lose a stack, and can no longer gain Sure-Fire Plan stacks.`,
        groupId: 22,
        talentTypeId: 2,
        createdAt: new Date(),
      },

      {
        name: "Ministorum Priest",
        description: `Grants 2x number of Steal stacks momentum. Then the priest gains WP bonus stacks of Zeal. Does not provoke attacks of opportunity. Whilst in combat priest gains +Willpower. Attacks with bolter, flamer, chain, melta or power deal per enemy attacked for the first time in combat. They gain +2 stacks of Zeal for xenos and daemons killed in combat. Unshakable Faith: in combat priest gains (2 x (STR, TGH, AGI, PER)) Willpower.`,
        groupId: 22,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Litany of Purification",
        description: `Whenever the character uses War Hymn or Furious Recital, each daemon and xenos in a 5-cell radius suffers 5 x Zeal stacks direct damage and +1 stack of Perplexed.`,
        groupId: 22,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Litany of Hatred",
        description: `Whenever the priest uses War Hymn, for 1 round, the priest and allies in a 5-cell radius deal + (number of Zeal stacks / 2) more weapon damage. This is doubled against daemons, psykers and xenos.`,
        groupId: 22,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Tenets of Retribution",
        description: `The priest deals +WP/3 more damage and WP% more critical damage with bolt weapons. Base melta weapon and flamer damage is increased by WP bonus%. These bonuses are doubled against daemons, psykers and xenos.`,
        groupId: 22,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "The Emperor Protects",
        description: `Priest's maximum wounds are increased by Willpower bonus.`,
        groupId: 22,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Flensing Faith",
        description: `Priest gains WP bonus% armour penetration with chain and power weapons. Critical hits scored with such weapons inflict WP bonus/2 levels of burning. Bonuses doubled vs xenos, daemons and psykers.`,
        groupId: 22,
        talentTypeId: 2,
        createdAt: new Date(),
      },

      {
        name: "Navy Officer",
        description: `For 1 round, the Navy officer and their allies in a 5-cell radius gain +2 deflection for each Archetype taken by the Navy officer. They also cannot be forcefully moved or overpenetrated. Can only be used once. +1 charge when the navy officer drops below 50% for the first time in combat.`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Stentorian Voice",
        description: `Enemies in a 5-cell radius around the navy officer whilst Brace effect lasts suffer -(10 x number of archetypes) Weapon Skill and Ballistic Skill.`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Evasive Manoeuvres",
        description: `All allies affected by Braced effect or by the navy officer non-attacking archetype abilities gain (10 + 2 x PER)% dodge for 1 round. Officer and braced allies do not provoke attacks of opportunity.`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Fleet Combat Training",
        description: `When the navy officer scores a critical hit or successfully parries an attack with their primary melee weapon, they immediately make an attack with their secondary weapon against the same enemy.`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Get off Me!",
        description: `Brace for Impact! also allows the Navy Officer to use any ranged weapon in threatened areas, knocks enemies prone, and pushes them 1 cell away during the effect.`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Get Into Cover!",
        description: `All allies affected by Brace for Impact! gain an extra turn with 0 AP and 3 MP and increase their cover efficiency by +20% for 1 round.`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },

      {
        name: "Noble",
        description: `The noble assigns one ally who will become their servant until the end of combat. Any time the noble's abilities affect the servant, the servant gains +5 to all characteristics until the start of the noble's next turn. Any time the servant attacks a target that the noble dealt damage to last turn, the servant gains +(10 + noble's FEL bonus)% critical hit chance against that target. Can only be used once per combat.`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "You. Do Something.",
        description: `If a noble uses an ability on their servant, the servant gains +1 AP next turn. Does not stack with itself.`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "You. Protect Me.",
        description: `If the noble and the servant are adjacent at the start of the noble's turn, they both gain temporary wounds equal to servant's TGH bonus or noble's FEL bonus depending on which is higher.`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "You. Go On.",
        description: `The noble's servant gains +2 movement points every turn.`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "You. Kill It.",
        description: `If the servant kills the target that the noble dealt damage to last turn, the noble gains +1 AP next turn.`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "You. You Are Next.",
        description: `If the servant has less than 30% maximum wounds, the noble can use You. Serve Me. once more in battle, designating a new servant and removing the effect from the previous one. The noble cannot designate a character who already was their servant this combat.`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },

      {
        name: "Sanctioned Psyker",
        description: `Sanctioned Psykers have reduced 20% chances to trigger psychic phenomena.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Psyker Minoris",
        description: `Each level of psy rating provides the psyker access to new psychic powers. It also strengthens damaging psychic powers. (Minoris level).`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Psyker Majoris",
        description: `Each level of psy rating provides the psyker access to new psychic powers. It also strengthens damaging psychic powers. (Majoris level).`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Psyker Terminus",
        description: `Each level of psy rating provides the psyker access to new psychic powers. It also strengthens damaging psychic powers. (Terminus level).`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Psyker Extremis",
        description: `Each level of psy rating provides the psyker access to new psychic powers. It also strengthens damaging psychic powers. (Extremis level).`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Still Mind",
        description: `The psyker's resolve is increased by +(WP bonus / 2) while veil degradation is 10 or lower.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Inscribed Soul",
        description: `The psyker gains the Inscribed Soul ability. It costs no AP but deals direct damage to the psyker equal to 25% of the psyker's maximum wounds. The next psychic power used after this ability will not trigger psychic phenomena or perils of the warp and will not degrade the veil.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Sacred Rituals",
        description: `Psychic powers have a 25% chance to regain AP spent on psychic powers when veil degradation is 10 or lower.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Blade of Light",
        description: `Force weapon attacks deal +psy rating more damage and have +(5 x psy rating)% more armour penetration.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Enforce Reality",
        description: `Usage of a heroic act by the psyker decreases veil degradation by INT bonus.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Psychic Barrage",
        description: `Whenever the psyker uses a damaging psychic power on targets that are 6 cells or farther from the psyker, the targets suffer an additional +BS bonus damage.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Second Sight",
        description: `The psyker's psychic powers that have a range of 2 cells or more have their range increased by +PER bonus.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Stabilising Factor",
        description: `The first psychic power used each turn increases veil degradation by 2 points less. If this talent reduces the effect on veil degradation to less than 0, veil degradation is instead decreased by 1.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Subtle Manipulation",
        description: `The psyker can use a damaging psychic power while being threatened by enemies in melee range without provoking attacks of opportunity. Non-damaging psychic powers do not provoke attacks of opportunity even without this talent.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Obscured Threat",
        description: `While the psyker is not in the target's line of sight, or the psyker is in cover, all resistance tests of the target suffer a -(4 x psy rating) penalty.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },

      {
        name: "Psyker - Biomancer",
        description: `The target gains +(10 + 4 × psyker’s psy rating) Strength and Toughness until the end of combat.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Adrenaline Surge",
        description: `On the first turn of every combat, all psychic powers of the biomancy discipline cost -1 action point.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Biophysical Distortion",
        description: `All the psyker's attacks, including damaging psychic powers, now poison enemies. This poison deals (4 x psy rating) damage every turn.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Sanguine Siphon",
        description: `Every time the psyker deals damage, they gain +1 stack of the Sanguine Siphon effect. If that damage was dealt to a target adjacent to the psyker, they gain +2 stacks instead. When the psyker suffers lethal damage, the stacks of Sanguine Siphon are removed to reduce this damage by -1 for each stack, until either all stacks are removed or the damage is no longer lethal.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Confer Immunity",
        description: `Whenever the psyker is healed or heals any ally, if the character being healed is already at full wounds, that character instead gains temporary wounds equal to the healing. These temporary wounds do not stack.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Corpus Conversion",
        description: `When an enemy adjacent to an ally dies, that ally gains a stacking Corpus Conversion effect. If multiple allies are adjacent to the dead enemy, one is selected at random. The psyker's next psychic power that targets only the target with Corpus Conversion will work as if the psyker's psy rating is +2 higher, will not damage the veil, will not trigger psychic phenomena or perils of the warp, and will remove -1 stack of Corpus Conversion from the target. (Note: appears to be bugged and may add +2 psy rating on every psyker buff).`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Pulse of Life",
        description: `Whenever the psyker heals themselves or another character with a psychic power or an effect applied by a psychic power, this healing can critically heal with a chance of (5 + 2 x WP bonus)%. This critical heal chance is increased by all effects that increase critical hit chance, and the amount healed is increased by the same value as critical damage.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Warp Saturation",
        description: `When the psyker's allies or the psyker themselves are under the effects of the psychic powers, they gain +5 Toughness for each such effect.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Deterioration",
        description: `Whenever an effect applied by the psyker increases the damage suffered by a target, this effect is increased by half (for example, a 20% increase turns into a 30% increase).`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },

      {
        name: "Psyker - Diviner",
        description: `The psyker increases the target's dodge and parry by +(3 + psyker’s PER bonus + 3 × psy rating)% until the end of combat.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Edge of Fate",
        description: `At the beginning of every combat, the psyker's allies gain +15% critical hit chance. The first critical hit removes this effect.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Fatebringer",
        description: `Allies under the effect of at least one psychic power gain an additional +(5 + 2 x psyker's psy rating)% armour penetration.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Flawless Plan",
        description: `Every 9th successful dodge and/or parry by the psyker and their allies combined grants the psyker +2 additional AP on the next turn.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Predicted Downfall",
        description: `The first dodge attempt of every enemy in combat suffers a -(7 x psyker's psy rating)% penalty.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Unnatural Luck",
        description: `When the psyker uses a Divination psychic power on an ally without an Unnatural Luck effect, that ally gains Unnatural Luck. Unnatural Luck: when the ally suffers a critical hit, it becomes a normal hit instead and the Unnatural Luck effect is removed.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },

      {
        name: "Psyker - Pyromancer",
        description: `The target suffers (1 + WP + 6 x psy rating) to (2 x WP bonus + 10 x psy rating) damage and gains the Warp Burn effect. This attack has (5 × psyker’s psy rating)% armour penetration. Warp Burn: 3 + WP + 3 x PSY rating.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Blazing Inferno",
        description: `The psyker's critical hit chance increases by +1% until the end of combat every time the psyker deals damage by any means.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Backdraft",
        description: `Whenever a psychic power used by the psyker deals damage, a random enemy within 2 cells from the initial target suffers half of this damage. That damage does not trigger this talent again.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Body of Flames",
        description: `The psyker gains +(8 x psy rating)% additional armour against fire damage and half this amount as additional armour against energy damage from las, melta, and plasma weapons.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Relentless Blaze",
        description: `When the psyker is burning, the psyker's psy rating is increased by +1, and the psyker's resolve is increased by 2. Damage from fire no longer reduces the psyker's momentum.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Burning Blood",
        description: `When the psyker uses a psychic power, all enemies adjacent to the psyker suffer (4 x psy rating) direct damage. The same also happens when the psyker suffers damage from burning, bleeding, or melee attacks.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Fire Within",
        description: `Every time the psyker kills or scores a critical hit against 8 creatures in one combat, the psyker's next attack (including attacking psychic powers) will cost 0 AP and have no cooldown.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },

      {
        name: "Melting Armour",
        description: `Every time an enemy suffers damage from the psyker, that enemy's armour is reduced by -5%. If the enemy's armour is already 0, this enemy's deflection is reduced by -1 instead. (May be buggy and not always apply armour strip).`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Sparks of the Greater Flame",
        description: `All damage-over-time effects applied by the psyker gain additional % based on psy rating and other talents (complex stacking rules). Critical hit chance is increased by all bonuses to critical hit chance.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Psyker - Sanctic",
        description: `All allies in a circle with a 5-cell radius gain (1 + psy rating) resolve until the end of combat. Every additional stack of this effect increases the resolve bonus by +2.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },

      {
        name: "Destined",
        description: `The psyker's armour increases by +5%. This bonus increases by +5% at the start of every turn of combat except the first.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Edge of Dawn",
        description: `Enemies adjacent to the psyker suffer +10% more damage.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Eternal Glory",
        description: `The first time that momentum reaches 200 during the psyker's turn, the psyker gains +5 to all characteristics, +1 to resolve, +1 to deflection, and +1 to all damage that the psyker deals until the end of combat.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Hymns of Hatred",
        description: `Critical hits scored by anyone within the psyker's line of sight (including the psyker themselves) increase the psyker's critical damage by +1% until the end of combat. Stacks.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Psalms of Heroes",
        description: `The psyker's psy rating is increased by +1 until the end of combat every time an ally uses a heroic act.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Sanctified Slayer",
        description: `The psyker's critical hit chance is increased by +Resolve%`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },

      {
        name: "Psyker - Telepath",
        description: `Deals 4 + (psyker’s WP bonus × (1 + psy rating)) to (4 + psyker's WP bonus × (1 + psy rating)) damage to the target.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Aftershock",
        description: `Every time the psyker deals mental damage from any source other than Aftershock, the target suffers half as much mental damage at the end of its next turn.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Mental Breach",
        description: `Enemies that have taken damage from the psyker at least once suffer a -20 penalty to all resistance tests against the psyker until the end of combat.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Mind Siege",
        description: `Enemies that have failed a Willpower resistance test against any of the psyker's psychic powers will suffer an additional +(4 x psy rating) mental damage every time they suffer mental damage until the end of combat.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Mind Thief",
        description: `Any time an enemy becomes a target of any particular psyker ability for the first time, this enemy suffers a -5 penalty to their Intelligence and Perception, and the psyker's Intelligence and Perception increase by +2 until the end of combat.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Pain Channelling",
        description: `Whenever the psyker kills an enemy with a psychic power dealing more damage than wounds of the target, the excess damage will be dealt to the enemy closest to the target.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Visions of Doom",
        description: `Enemies that become targets of the psyker's psychic powers gain a stacking -5% penalty to their dodge and parry until the end of combat.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Warp Minds",
        description: `After every sixth use of a psychic power by the psyker, all enemies gain a stacking -5 penalty to all characteristics until the end of combat.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Weak Hearts",
        description: `Enemies currently inflicted with blinded, stunned, immobilised, or prone effects by the psyker suffer +10% more damage.`,
        groupId: 16,
        talentTypeId: 2,
        createdAt: new Date(),
      },

      {
        name: "Warrior",
        description: ``,
        groupId: 29,
        talentTypeId: 6,
        createdAt: new Date(),
      },
      {
        name: "Contempt",
        description: `Whenever an enemy attacks the Warrior, the Warrior's next melee attack against that enemy deals an additional +TGH bonus damage. Does not stack, but it can be reactivated after another attack made by either the same enemy or a different one.`,
        groupId: 29,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Desolation",
        description: `The Warrior deals an additional +AGI bonus damage to enemies that have no allies in adjacent cells.`,
        groupId: 29,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Easy Target",
        description: `The Warrior's critical damage is increased by +(10 + 2 × STR bonus)% against enemies not armed with a melee weapon.`,
        groupId: 29,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Enrage",
        description: `If the Warrior has less than 50% wounds, they gain +(5 + (TGH bonus + AGI bonus))% critical hit chance.`,
        groupId: 29,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Epicentre of Slaughter",
        description: `Whenever the Warrior is attacked, they gain +1 stack of Epicentre of Slaughter until the end of combat. At the start of their turn, the Warrior gains +1 temporary wound for each stack. These temporary wounds cannot exceed the Warrior's TGH bonus.`,
        groupId: 29,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Thick Skin",
        description: `The Warrior gains +1 damage deflection. Their parry chance is increased by +25% of the Warrior's total armour.`,
        groupId: 29,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Blade Flurry",
        description: `Each use of Slash increases the damage dealt by Slash by +1 until the end of combat.`,
        groupId: 29,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Cautious Disengage",
        description: `Attacks of opportunity deal -(10 + 3 x WS bonus)% less damage to the Warrior. Movement within range of attacks of opportunity costs -1 MP less.`,
        groupId: 29,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Clenched Teeth",
        description: `The Warrior gains +TGH bonus damage deflection against the first attack made by every enemy this combat.`,
        groupId: 29,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Crowd Kill",
        description: `Area attacks deal an additional +(1 + STR bonus / 2) damage for each enemy in the area of effect.`,
        groupId: 29,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Defensive Manoeuvres",
        description: `When the Warrior takes damage, they gain +(5 + 2 x AGI bonus)% dodge. Stacks up to 3 times and resets after a successful dodge.`,
        groupId: 29,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Defensive Stance",
        description: `If the Warrior has not attacked this turn, they gain +(10 + 2 x TGH bonus)% armour. Charge and Slash do not affect this bonus.`,
        groupId: 29,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Disarm",
        description: `When the Warrior uses a single-shot or melee attack against a target, the Warrior gains +(5 + 2 x TGH bonus)% armour against attacks made by that target for 1 round.`,
        groupId: 29,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Field Medic",
        description: `Allows the Fighter to use Medikits without Medicae Skill. The Fighter also regains additional Wounds equal to their TGH Bonus whenever the Medikit is used on them.`,
        groupId: 29,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Hardened Scars",
        description: `Whenever the Warrior is hit while under the Endure effect, their damage deflection is increased by +1 until the Warrior's next turn.`,
        groupId: 29,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Impetus",
        description: `The damage dealt by Charge is increased by +(TGH bonus + STR bonus) when the ability is used from a distance of 5 or more cells.`,
        groupId: 29,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Interception",
        description: `When the Warrior parries an attack, their next Warrior archetype ability costs -1 AP less.`,
        groupId: 29,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Invigorating Hatred",
        description: `When the Warrior ends their turn near an enemy affected by the Sworn Enemy ability, the Warrior gains +(2 + TGH bonus) temporary wounds.`,
        groupId: 29,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Living Shield",
        description: `Enemies suffer a -10% penalty to their hit chance with ranged attacks (including area attacks) against the Warrior for every enemy in a 1-cell radius around the Warrior. Stacks up to 3 times.`,
        groupId: 29,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Open Engagement",
        description: `If there are no enemies adjacent to the Warrior at the start of the turn, the Warrior's damage is increased by +(2 x STR bonus) for one melee attack.`,
        groupId: 29,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Opening Strike",
        description: `Charge and Push increase the damage of ranged attacks made against affected enemies by +(5 + WS bonus)% until the end of combat. Does not stack.`,
        groupId: 29,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Ramming Speed",
        description: `Increases Charge distance by +3 cells.`,
        groupId: 29,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Reckless Fury",
        description: `Whenever the Warrior hits with Reckless Strike, this attack scores a guaranteed critical hit.`,
        groupId: 29,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Rigorous Training",
        description: `The Warrior becomes incredibly deft. Charge and Slash do not end the Warrior's movement and grant +(10 + AGI bonus)% dodge for 1 round after use.`,
        groupId: 29,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Shearing Strikes",
        description: `When the Warrior uses Slash with two melee weapons equipped, the Warrior deals damage from both weapons. (Currently bugged and does not work with Rigorous Training).`,
        groupId: 29,
        talentTypeId: 2,
        createdAt: new Date(),
      },

      // Officer talents follow...
      {
        name: "Blood Of Martyrs",
        description: `Whenever an ally uses a heroic act, that ally gains temporary wounds equal to (10% of their maximum wounds + Resolve).`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Commanding Voice",
        description: `The range of the Officer's abilities is increased by +3. The range of Voice of Command is increased by +6.`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Focus!",
        description: `Whenever the Officer uses an ability on an ally, that ally gains a bonus to their Perception and Ballistic Skill equal to 2 + (Officer's Resolve Bonus / 2). These bonuses stack, but half of the stacks (rounded up) are lost at the end of the target's turn.`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Inspire Courage",
        description: `Whenever the Officer targets an ally with an ability for the first time in a round, that ally gains +WP bonus temporary wounds.`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Personal Oversight",
        description: `Whenever the Officer targets an ally with an action (an ability or an attack), that ally's resolve is increased by +1 until the end of the Officer's next turn. This effect stacks and is prolonged until the end of the Officer's next turn each time it stacks. Cannot be prolonged past the Officer's next turn.`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Steel Resolve",
        description: `The Officer's resolve is increased by +3.`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Armour of Contempt",
        description: `Whenever an ally is affected by an Officer's ability or talent that grants temporary wounds, that ally's armour is increased by +10% for 1 round. Does not stack.`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Be Vigilant!",
        description: `Allies under the effect of the Officer's abilities gain a bonus to their Weapon Skill equal to (3 + Officer's FEL bonus) and will deal +FEL bonus more damage on attacks of opportunity until the start of the Officer's next turn.`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Decisive Response",
        description: `Whenever the officer uses Voice of Command or Bring It Down! for the first time in combat, this ability costs -1 AP.`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Heroism",
        description: `Whenever a heroic act is used in combat by any character, the Officer's next attack will cost 0 AP.`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Inspiring Speech",
        description: `Air of Authority immediately grants momentum to the target equal to the target's resolve.`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Iron Discipline",
        description: `Allies affected by the Officer's abilities gain a bonus to all resistance tests equal to (2 x Officer's WP bonus).`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Lasting Impression",
        description: `Half of the bonus granted by the Voice of Command remains until the end of combat. This bonus does not stack with itself or with bonuses granted by Voice of Command but does count as an Officer ability effect for the purposes of other talent effects.`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Lead by Example",
        description: `Whenever the Officer uses an Officer archetype ability two times in one turn that does not grant an extra turn, they gain the Stand Witness effect. Stand Witness: the next Officer archetype ability that does not grant an extra turn will also affect the Officer.`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Leader's Assault",
        description: `Whenever the Officer makes an attack, they gain +5 Fellowship until the end of combat.`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "March",
        description: `Whenever the Officer's ability moves any target, the Officer gains movement points equal to half the distance the target moved. If this happens on another character's turn, the Officer will gain these movement points on their next turn.`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "No Respite",
        description: `Whenever the Officer's ability grants action points to an ally, that ally also gains +1 to all characteristics for every action point gained until the end of combat.`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Physical Encouragement",
        description: `Whenever an ally starts a turn (including any extra turn) adjacent to the Officer, that ally gains additional MP equal to (Officer's FEL bonus / 2).`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Prepare for an assault!",
        description: `Break Their Ranks! works as if there were one more enemy adjacent to the target. This allows this ability to be used on targets with no enemies adjacent to them.`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Seize the initiative",
        description: `Allow officers and allies under the effect of the Officer's Voice of Command to deal additional damage to enemies that have not yet acted in this combat.`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Steady!",
        description: `Take Aim! also increases the damage of the next ranged attack by 5% + 1% for each cell between the attacker and the target.`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Undaunted",
        description: `The Officer gains +10 Willpower and +10 Fellowship when they have less than 50% of their maximum wounds remaining. They also gain an additional +10 Willpower and +10 Fellowship after using any officer ability on a target with less than 50% wounds for 1 round. These two sets of bonuses stack with each other but do not stack with themselves.`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Watch Yourself!",
        description: `Targets of Move, Move, Move! gain a +10% bonus to dodge and a +10% bonus to cover efficiency until the start of the Officer's next turn.`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Wounds Are No Excuse!",
        description: `Get Back in the Fight! removes 1 fresh injury from the target and heals the target for (Officer's WP bonus / 2) wounds for each condition removed by Get Back in the Fight! (including fresh injuries). A minimum of (Officer's WP bonus / 2) wounds is always healed, even if no conditions are removed.`,
        groupId: 30,
        talentTypeId: 2,
        createdAt: new Date(),
      },

      // Operative talents
      {
        name: "Fresh Target",
        description: `Whenever the Operative attacks an enemy that is at full wounds, that attack deals +(10 + PER bonus)% more damage to that enemy.`,
        groupId: 31,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Instant Exposure",
        description: `Expose Weakness costs 0 AP.`,
        groupId: 31,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Tide of Excellence",
        description: `Whenever the Operative triggers an exploit on an enemy, the Operative gains +1 damage and +2% armour penetration until the end of combat. Stacks.`,
        groupId: 31,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Weak Body, Weak Soul",
        description: `Expose Weakness also reduces enemies' Toughness and Willpower by -(3 x INT bonus) for 1 round.`,
        groupId: 31,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Ballistics Calculation",
        description: `If the Operative attacks a target affected by an exploit from a distance of (15 - PER bonus) cells or farther, that attack deals +15% damage.`,
        groupId: 31,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Combat Insight",
        description: `While the Operative's Perception bonus is 10 or higher, they gain +1 AP and ignore enemies' deflection.`,
        groupId: 31,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Comprehensive Analysis",
        description: `If the target of Analyse Enemies has 2 or more exploits, that target suffers +1 additional exploit.`,
        groupId: 31,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Continuous Analysis",
        description: `At the start of the Operative's turn, the enemy with the largest number of exploits receives an additional exploit stack. If two or more enemies are tied for the largest number of exploit stacks, one of those enemies is chosen at random.`,
        groupId: 31,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Covert Protocol",
        description: `While the Operative is in half cover, their cover efficiency is increased by +15%. This bonus is doubled if the Operative has not moved during their turn.`,
        groupId: 31,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Improved Tactics",
        description: `Tactical Knowledge requires 3 exploits instead of 4. The Operative's damage is increased by +INT bonus.`,
        groupId: 31,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Inflict Despair",
        description: `Whenever the Operative hits an enemy that is affected by both an exploit and Expose Weakness, that enemy loses -3 MP and their damage is reduced by -20% on their next turn.`,
        groupId: 31,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Informed Hit",
        description: `If the Operative uses Precise Attack on a target affected by (10 - INT bonus) or more exploits and scores a hit, that hit becomes a critical hit.`,
        groupId: 31,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Insightful Precision",
        description: `Precise Attack grants the Operative a bonus to Perception equal to (number of exploits removed / 2) (minimum 1).`,
        groupId: 31,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Joint Offensive",
        description: `The Operative's allies gain +Operative's INT bonus / 2 hit chance and critical hit chance while attacking targets affected by exploits.`,
        groupId: 31,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Offensive Pattern Prediction",
        description: `The Operative suffers -(5 + INT bonus)% less damage from enemies affected by exploits.`,
        groupId: 31,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Passive Learning",
        description: `On their first turn in combat, the Operative randomly distributes the same number of exploits as when using Analyse Enemies among all enemies in a 10-cell radius around the Operative. At the start of each of the Operative's subsequent turns, they distribute half as many exploits (half the base amount) among all enemies in a 2-cell radius around the Operative.`,
        groupId: 31,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Reactive Study",
        description: `If an enemy affected by an exploit within 5 cells from the Operative attacks the Operative or their ally, that enemy suffers +1 additional exploit.`,
        groupId: 31,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Sharpshooter",
        description: `If the Operative has not moved this turn, they gain +PER bonus Ballistic Skill and +(INT bonus / 2) damage for every 5 cells between them and the target.`,
        groupId: 31,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Sniper Expertise",
        description: `Perfect Spot additionally grants the Operative +(5 + PER bonus)% armour penetration against enemies that are 7 cells away or farther.`,
        groupId: 31,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Terrifying Presence",
        description: `If Intimidation kills the target, the damage of all other enemies in the area of Intimidation is reduced by an additional -(4 x INT bonus)%.`,
        groupId: 31,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Uncanny Sight",
        description: `The Operative inflicts an exploit even on enemies which are out of the Operative's line of sight at the start of the turn.`,
        groupId: 31,
        talentTypeId: 2,
        createdAt: new Date(),
      },

    ];


  const batchSize = 15;
  for (let i = 0; i < talents.length; i += batchSize) {
    const batch = talents.slice(i, i + batchSize);
    if (batch.length) {
      await db.insert(tables.talents).values(batch);
    }
  }

}
