export const archmilitant = [
{
    name: "Always Ready",
    description: `The Arch-Militant begins combat with 2 stacks of versatility.`,
    groupId: 40,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Broad Expertise",
    description: `When entering combat the Arch-Militant gains +(2 X BS bonus) Weapon Skill, and +(2 X WS bonus) Ballistic Skill until end of combat.`,
    groupId: 40,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Critical Versatility",
    description: `The Arch-Militant gains a +(5 + number of Versatility stacks)% bonus to critical damage. This bonus is kept when the Arch-Militant uses Cautious Approach or Confident Approach.`,
    groupId: 40,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Dependable",
    description: `The Arch-Militant gains a +(5 + stack of versatility)% bonus to armour. This bonus is kept when the Arch-Militant uses Cautious Approach or Confident Approach.`,
    groupId: 40,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Exploit Weakness",
    description: `When the Arch-Militant attacks targets that have their armour reduced by any effects applied by the Arch-Militant's allies, the Arch-Militant deals +10% damage. When the Arch-Militant attacks targets that have their deflection reduced by any effects applied by the Arch-Militant's allies, the Arch-Militant deals +2 damage.`,
    groupId: 40,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Preferred Targets",
    description: `When the Arch-Militant attacks targets that have their dodge reduced by any effects applied by the Arch-Militant's allies, the Arch-Militant gains +10% critical hit chance. When the Arch-Militant attacks targets that have their parry reduced by any effects applied by the Arch-Militant's allies, the Arch-Militant deals +20% critical damage.`,
    groupId: 40,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Accustomed to Glory",
    description: `Whenever the Arch-Militant or their ally uses a heroic act or a desperate measure, the Arch-Militant gains +1 and +10 damage for all attacks until the end of combat.`,
    groupId: 40,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Adaptability",
    description: `Gaining a stack of versatility increases critical hit chance by +5% until the end turn. Stacks.`,
    groupId: 40,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "All Out",
    description: `While the Arch-Militant is under the effects of Reckless Rush, their attacks do not cost MP.`,
    groupId: 40,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Armsmaster",
    description: `Killing an enemy with a melee attack makes all the Arch-Militant's ranged attacks this turn cost -1 AP (min 1), and vice versa. Does not stack.`,
    groupId: 40,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Awaiting Orders",
    description: `Every round, the first single-target ability used by an ally on the Arch-Militant grants +1 action point to that ally.`,
    groupId: 40,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Blood Haze",
    description: `As long as the Arch-Militant has killed at least one enemy with a melee attack this round, the Arch-Militant gains a +(10 + AGI bonus)% bonus to dodge.`,
    groupId: 40,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Breaking Attack",
    description: `Devastating Attack also reduces the target's armour by -7% and Toughness by -10 until the end of combat. Does not stack.`,
    groupId: 40,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Calm and Steady",
    description: `While under the effect of Confident Approach, the Arch-Militant keeps half of the usual bonuses from versatility.`,
    groupId: 40,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Close-Quarters Training",
    description: `The Arch-Militant can use two-handed ranged weapons within melee range but with a -10 penalty to Ballistic Skill.`,
    groupId: 40,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Contempt for the Weak",
    description: `The Arch-Militant deals +20% critical damage against targets that are stunned, prone, or blinded.`,
    groupId: 40,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Crippling Blasts",
    description: `Any ranged area and burst attacks of the Arch-Militant reduce the Weapon Skill of all enemies hit by -10 until the end of combat. Does not stack.`,
    groupId: 40,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Discipline",
    description: `The Arch-Militant gains +1 stack of versatility whenever an ally grants the Arch-Militant an extra turn.`,
    groupId: 40,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Dismantle",
    description: `Any of the Arch-Militant's area attacks, both melee and ranged, reduce the deflection of all the enemies hit by -2 and their armour by -7% until the end of combat. Does not stack.`,
    groupId: 40,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Distract",
    description: `Any of the Arch-Militant's burst attacks and melee area attacks reduce dodge of all the enemies hit by -8% until the end of combat. Does not stack.`,
    groupId: 40,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Flashfire",
    description: `The cost of Wildfire is reduced by -1 AP for every 3 stacks of versatility instead of 4.`,
    groupId: 40,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Focal Point",
    description: `The Arch-Militant deals +15% damage to targets that have a priority target regardless of whether that target is the Arch-Militant or someone else.`,
    groupId: 40,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Heavy Gunner",
    description: `The Arch-Militant's heavy weapon attacks cost -1 action point.`,
    groupId: 40,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Ingenious",
    description: `Enemies that were forced to make a resistance test by the Arch-Militant will make any resistance tests from any source with a -(10 + 2 X AGI bonus) penalty until the end of combat.`,
    groupId: 40,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Martial Art",
    description: `Targets of Kick must pass a Toughness resistance test with a -(2 X Arch-Militant's STR bonus) penalty or fall prone for 1 round.`,
    groupId: 40,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Survivor",
    description: `Using Cautious Approach also grants the Arch-Militant temporary wounds equal to 10% of the Arch-Militant's maximum wounds. The same happens at the start of every turn while the Arch-Militant remains under the effect of Cautious Approach.`,
    groupId: 40,
    talentTypeId: 2,
    createdAt: new Date(),
  },
]
