export const assassin = [
  {
    name: "An Eye for the unscathed",
    description: `Whenever the Assassin attacks an enemy that is at full wounds, the Assassin gains +20% dodge and dodge reduction against that enemy until the end of the Assassin's next turn.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Bringer of Doom",
    description: `Whenever the Assassin attacks an enemy with a single-target attack, this attack reduces the target's armour and dodge by -15% until the end of the Assassin's turn. Does not stack.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Create an opening",
    description: `If an enemy suffers a critical hit from one of the Assassin's allies, at the start of the Assassin's turn, a new opening is created on whichever side is closest to the Assassin.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Inevitable Enervation",
    description: `Each use of Aim for the Opening on the same target reduces that target‘s dodge and dodge reduction by -10%. Stacks.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Perfect Opening",
    description: `The Assassin gains +Lethality% chance to deal +5% of target's max wounds more damage to an opening.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Professional Acumen",
    description: `Every turn, the first use of an Assassin ability costs 0 AP.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Ambush",
    description: `At the start of the Assassin's turn, all enemies that do not have the Assassin in their line of sight suffer the unsuspecting effect until the end of the Assassin's turn. Unsuspecting: the Assassin gains +7% hit chance and +7% critical hit chance against unsuspecting enemies.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Carmine Whisper",
    description: `The haemorrhage effect applied by Death Whisper deals an additional +10 damage.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Deadly Calculation",
    description: `For every 10 damage dealt by an Assassin's attack, that attack also deal +1 direct damage to the same target. Direct Damage: damage that cannot be reduced by the target's parameters or bonuses.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Disarray",
    description: `Whenever the Assassin deals direct damage, the target must pass an Agility resistance test with a -(2 X Assassin's AGI bonus) penalty or become slowed until the end of their next turn.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Elusive Speed",
    description: `If the Assassin is elusive at the start of their turn, they gain +4 MP and +10 lethality until the end of their turn.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Esquieve",
    description: `Each successful dodge grants the Assassin +(Lethality / 5)% damage for the next successful attack.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Flawless Lunge",
    description: `Poised to Strike also reduces the target's dodge by -(2 X AGI bonus)%.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Gruesome Gust",
    description: `The armour penetration penalty of Feinting Attack is reduced to -20%.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Imminent Demise",
    description: `Whenever the Assassin deals direct damage to an enemy, that enemy suffers +1 stack of the vulnerable effect. Vulnerable: the character suffers +(number of vulnerable stacks) X PER bonus% more damage from the Assassin's attacks. Direct Damage: damage that cannot be reduced by the target's parameters or bonuses.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Keep your distance",
    description: `Whenever the Assassin has no more than 1 adjacent enemy, any enemy that moves into a cell adjacent to the Assassin must pass an Agility resistance test with a -(2 X STR bonus) penalty or fall prone, if possible, and become immobilised until the start of that enemy's next turn.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Killing Spree",
    description: `Whenever the Assassin hits an opening, the Assassin's damage is increased by +(AGI bonus / 2)% until the end of combat. Stacks.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Leave no witness",
    description: `The enemy last damaged by the Assassin suffers the witness effect. Witness: if a witness does not have the Assassin in their line of sight at the end of the Assassin's turn, that witness suffers (lethality / 3)% of the maximum base damage of the Assassin's current weapon.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Lethality Heightens",
    description: `Whenever the Assassin deals 5 or more direct damage to an enemy with a single attack, the Assassin gains +10 lethality until the end of combat. Stacks.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Lone Killer",
    description: `While the Assassin has no allies in a 5-cell radius around them, they gain +10% dodge and +10% dodge reduction.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Morbid Pirouette",
    description: `Danse Macabre deals additional +AGI bonus direct damage.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Mortally Effective",
    description: `Whenever the Assassin hits a target with an attack that has 100 lethality or greater for the first time in a round, the Assassin immediately regains the AP spent for that attack.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Outsmart",
    description: `Whenever the Assassin hits an enemy without hitting the enemy's opening, the Assassin gains +2 X (AGI bonus)% dodge until the start of their next turn.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Seize the advantage",
    description: `The Assassin gains +15 lethality against enemies that have any of following effects: slowed, immobilised, or haemorrhage. The bonus is gained for each of these effects but cannot exceed +45 lethality.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
]
