export const bladedancer = [
  {
    name: "Death From Above",
    description: `The Bladedancer leaps into the air and lands on the selected cell. Upon landing, they deal (AGI bonus + WS bonus) damage to all adjacent enemies.
This leap can be made to any unoccupied cell within a 3-cell radius in the Bladedancer's line of sight. This movement does not provoke attacks of opportunity. The Bladedancer cannot jump to a cell that is inaccessible in combat.
This ability can be used multiple times per turn, but each use requires a charge to be spent. The Bladedancer gains +1 charge of this ability each time they kill a target (excluding kills made with Death From Above). This ability can only be used with a sword equipped.`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Bladedance",
    description: `The Bladedancer makes (2 + AGI bonus/4) melee attacks against random targets (including allies) adjacent to the Bladedancer, each dealing 50% of their normal damage. Blade Dance is a melee burst attack that does not count toward the attack limit per turn.
This ability can only be used with a sword equipped. If two swords are equipped, the Bladedancer makes (1 + AGI bonus/4) attacks with each one.`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Acrobatic Artistry",
    description: `The Bladedancer immediately returns to the cell where they started their turn. This movement does not provoke attacks of opportunity. If the Bladedancer used Death From Above this turn, this movement repeats all uses of this ability in reverse.`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Oath of Vengeance",
    description: `This ability costs (5 + Bladedancer's level / 2) wounds to use.
The Bladedancer selects an ally. Until the end of combat, attacks made by the Bladedancer against enemies who have already attacked that ally gain +(10 + AGI bonus)% critical hit chance and +(20 + 2 x WS bonus)% critical damage.
This ability can be used multiple times per turn, but the bonuses do not stack.`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Veil of Blades",
    description: `This ability costs (5 + Bladedancer's level / 2) wounds to use.
The Bladedancer faces a side of their choice and immediately ends their turn. Until the beginning of the Bladedancer's next turn, they can dodge area attacks without moving, are immune to all types of forced movement, gain +20% parry against attacks from that side, and can now parry attacks made against adjacent allies. While under the effect of Veil of Blades, the Bladedancer can even parry ranged attacks (except ranged area attacks) made from that side. The chance to parry a ranged attack is calculated as if it were a melee attack, where the attacker's Weapon Skill is equal to the hit chance of the attack. If an attack is parried in this way, it can be redirected towards one of the enemies on the selected side. The chance of redirection is equal to half of the Bladedancer's parry chance against this attack.
This ability can only be used with a sword equipped.`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Blood Oath",
    description: `This ability costs (5 + Bladedancer's level / 2) wounds to use.
The Bladedancer targets a single enemy, vowing to dispatch their mark. The Bladedancer's next attack against their selected enemy cannot be dodged or parried. If this attack kills the target, the Bladedancer regains +(5 + 2 x TGH bonus) wounds and gains +1 AP along with an additional attack this turn.
This ability can be used multiple times per turn, but it grants +1 AP and an additional attack only once per round.`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Captive Audience",
    description: `The Bladedancer's next attack inflicts bleeding (AGI bonus + WS bonus) on all targets hit. These targets must pass a Toughness resistance test with a -(10 + 2 x AGI bonus) penalty or become immobilised for 1 round. All enemies immobilised by Captive Audience count as full cover for the Bladedancer and their allies when adjacent to those enemies.`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },

  {
    name: "Death Waltz",
    description: ``,
    groupId: 31,
    talentTypeId: 5,
    createdAt: new Date(),
  },
  {
    name: "Death Waltz I",
    description: ``,
    groupId: 31,
    talentTypeId: 5,
    createdAt: new Date(),
  },
  {
    name: "Death Waltz II",
    description: ``,
    groupId: 31,
    talentTypeId: 5,
    createdAt: new Date(),
  },
  {
    name: "Death Waltz III",
    description: ``,
    groupId: 31,
    talentTypeId: 5,
    createdAt: new Date(),
  },
  {
    name: "Death Waltz IV",
    description: ``,
    groupId: 31,
    talentTypeId: 5,
    createdAt: new Date(),
  },
  {
    name: "Blade in his hand",
    description: `Any Bladedancer attacks made with a sword deal + AGI bonus% additional damage. This bonus damage is doubled if using a two-handed sword.`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Blinding blades",
    description: `Enemies attacked by the Bladedancer have their Weapon Skill, Ballistic Skill, and Perception reduced by -(10 + Bladedancer's WS bonus) until the start of the Bladedancer's next turn. These penalties do not stack.`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Death Warden",
    description: `The Bladedancer's Medicae is now determined by Weapon Skill instead of Intelligence (if their Weapon Skill is higher). The Bladedancer deals +(5 + Medicae / 10)% critical damage and can use medikits as if having Medicae skill advancement or the corresponding feature or talent.`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Race Against Death",
    description: `The Bladedancer's maximum wounds are increased by +(Bladedancer's dodge/10).`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Rising Tempo",
    description: `Each attack made by the Bladedancer increases the damage of all subsequent attacks they make this turn by +5%. This effect stacks up to 3 times. Area attacks, burst attacks (including the Blade Dance), and any other attacks that deal multiple hits are considered single attacks.`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Steady Hand",
    description: `The Bladedancer's parry is increased by +TGH bonus%. An attacker's melee critical hit chance bonus determined by the difference between the attacker's and the Bladedancer's Weapon Skill characteristic is halved.`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Sweeping Motions",
    description: `The Bladedancer's melee area attacks cost -1 AP less (but not less than 1).`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Anticipation",
    description: `Whenever the Bladedancer parries a melee attack while under the effect of Veil of Blades, they deal 50% of their normal damage to the attack. Additionally, while under the effect of Veil of Blades, the Bladedancer's chance to deflect a ranged attack at an enemy is increased by +20%.`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Balancing on the Edge",
    description: `The Bladedancer can use both a desperate measure and a heroic act in the same combat (but not in the same round). Whenever the Bladedancer uses a desperate measure, they gain +10 Weapon Skill and +3 resolve.`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Blessed Scars",
    description: `Whenever the Bladedancer is healed for the first time in a round, they are healed for an additional +TGH bonus wounds and gain +10 Toughness until the end of combat. Stacks.`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Blood Bonds",
    description: `Every ally targeted by Oath of Vengeance gains the same bonuses as the Bladedancer against all affected enemies.`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Blood Rush",
    description: `Whenever the Bladedancer uses an ability that costs wounds, they gain +3 MP in the current turn.`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Bloody Requiem",
    description: `Whenever the Bladedancer kills an enemy, the Bladedancer's resolve is increased by +1 until the end of combat.`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Dance Partners",
    description: `As long as the Bladedancer has two swords equipped, the Bladedancer's Weapon Skill is increased by +AGI bonus.`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Duellist",
    description: `The Bladedancer deals an additional +(5 + Bladedancer's WS bonus)% damage against enemies armed with a melee weapon.`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Escape Artist",
    description: `Whenever the Bladedancer dodges an attack made by an enemy who attacks them for the first time, the Bladedancer gains +1 charge of Death From Above.`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Facing the End",
    description: `The Bladedancer gains +3 Weapon Skill and +3 Agility for every injury they are currently suffering and +10 Weapon Skill and +10 Agility for every trauma.`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Feel No Pain",
    description: `Whenever the Bladedancer uses an ability that costs wounds, they gain half of the wounds spent as temporary wounds. The number of temporary wounds gained cannot be decreased by effects that reduce the cost of abilities.`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Grand Performance",
    description: `Targets affected by Captive Audience have their armour, dodge, and parry reduced by -(10 + AGI bonus)% until the end of combat. This penalty is doubled for targets failing the ability's Toughness resistance test.`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Guillotine",
    description: `Death From Above deals double damage to enemies that have less than 50% wounds.`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "In Footseps of Death",
    description: `Every time an enemy is killed by Bladedancer's allies, the amount of Movement Points Bladedancer gets on their next turn increases by 2.`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "It Takes Two",
    description: `If all the strikes made as part of Blade Dance are directed against the same target, the last strike deals double damage.`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Killing Rhythm",
    description: `Whenever the Bladedancer kills an enemy with an attack of opportunity, the Bladedancer immediately gains +1 charge of Death From Above.`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Paid In blood",
    description: `Once the Bladedancer has killed four enemies in total, the next ability which requires spending wounds will cost no wounds and instead restore (5 + 2 x TGH bonus) wounds.`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Promises of blood",
    description: `Blood Oath restores an additional +1 AP.`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Shadow Dancer",
    description: `As long as the Bladedancer has less than 50% wounds, they gain +12% dodge and +3 MP. The Bladedancer also gains +8% dodge and +2 MP for every unconscious ally in combat.`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Slip Away",
    description: `Whenever the Bladedancer uses Acrobatic Artistry, their dodge and cover efficiency are increased by +(5 + AGI bonus)% until the end of their next turn. This bonus is doubled against all attacks made by enemies during the Bladedancer's turn (including extra turns).`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Spinning Blades",
    description: `Whenever the Bladedancer parries an attack, the number of attacks made by the next Blade Dance is increased by +1. This effect stacks up to AGI bonus times.`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Unforgiving",
    description: `After the Bladedancer loses any number of wounds, their next attack deals +(5 + TGH bonus)% more damage. If that loss causes the Bladedancer to suffer an injury or trauma, the bonus damage increases to +(10 + 2 x TGH bonus)%.`,
    groupId: 33,
    talentTypeId: 2,
    createdAt: new Date(),
  },
]



