export const bountyhunter = [
        {
        name: "Gruesome Kill",
        description: `Whenever prey is killed, all enemies in a 10-cell radius around the prey have their Agility reduced by -(5 X prey's difficulty tier) for 2 rounds.`,
        groupId: 37,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Heightened Concentration",
        description: `Whenever the Bounty Hunter scores a critical hit, they gain +PER bonus% armour penetration until the end of combat. Stacks.`,
        groupId: 37,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Hunting Surge",
        description: `Whenever an enemy is killed by a critical hit scored by the Bounty Hunter or their ally, the Bounty Hunter gains +(2 X enemy's difficulty tier)% damage for 2 rounds.`,
        groupId: 37,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Pierce the Armour",
        description: `Each enemy affected by Piercing Shot has their armour reduced by -BS bonus% until the end of combat. Stacks.`,
        groupId: 37,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Share the Spoils",
        description: `Whenever an ally kills prey, the Bounty Hunter gains half of the bonuses granted by Hunt Down the Prey.`,
        groupId: 37,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Withdraw",
        description: `Whenever the Bounty Hunter is attacked in melee range for the first time since the end of their turn, they automatically dodge that attack and move 1 cell in the opposite direction from the enemy. The Bounty Hunter does not provoke attack of opportunity with this movement.`,
        groupId: 37,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Catch",
        description: `Whenever the Bounty Hunter hits an enemy with an attack, they inflict the catch effect on that enemy. Catch: at the start of the Bounty Hunter's turn, this target suffers a stacking -(2 X (catch's difficulty tier + PER bonus))% penalty to their armour and dodge. Once the catch moves or suffers damage, the catch effect and the penalties are removed.`,
        groupId: 37,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Claim and Maim",
        description: `If Claim the Bounty kills an enemy, the Bounty Hunter's next attack this turn will always score a critical hit.`,
        groupId: 37,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Critical Chain",
        description: `Whenever the Bounty Hunter kills an enemy with a critical hit, all allies in a 7-cell radius around the target gain +target‘s difficulty tier% critical hit chance until the end of combat. Stacks.`,
        groupId: 37,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Cut to the chase",
        description: `Whenever the Bounty Hunter scores a critical hit for the first time in a round, they gain +target's difficulty tier movement points.`,
        groupId: 37,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Expert Finesse",
        description: `Whenever the Bounty Hunter kills an enemy whose difficulty tier is IV or higher, the Bounty Hunter immediately reloads their weapon and attacks the closest enemy in their line of sight. This attack gains +50% overpenetration but deals only (4 x (BS bonus + PER bonus))% of the Bounty Hunter's usual damage.`,
        groupId: 37,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Flay The Bold",
        description: `Cull the Bold additionally removes -target's difficulty tier deflection, -(2 X target's difficulty tier) Willpower, and -(2 X target's difficulty tier) Toughness from the target.`,
        groupId: 37,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Guidance",
        description: `The Bounty Hunter's first critical hit in a round grants their allies a stacking +(target's difficulty tier + Bounty Hunter's PER bonus / 3)% bonus to armour penetration until the end of combat. Once a character with this bonus reloads, the bonus is removed.`,
        groupId: 37,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Hunter's Ambush",
        description: `When the Bounty Hunter performs a single-shot attack on an immobilised or stunned target, this attack refunds its cost and does not count for the attack limit. Once per round.`,
        groupId: 37,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Inspiring Trophy",
        description: `Whenever the Bounty Hunter kills prey whose difficulty tier is IV or higher, the Bounty Hunter additionally gains +2 AP.`,
        groupId: 37,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Kill Squad",
        description: `Raid grants an ally an additional +(2 X prey's difficulty tier)% damage against prey.`,
        groupId: 37,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Pierce and Ruin",
        description: `Whenever the Bounty Hunter scores a critical hit, the target's armour is reduced by -(BS bonus + target's difficulty tier)% until the end of combat. Stacks.`,
        groupId: 37,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Pounce",
        description: `The Bounty Hunter's allies gain +(3 + Bounty Hunter's PER bonus) critical hit chance against enemies affected with one or more of the following effects: prey, trailed, or immobilised.`,
        groupId: 37,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Retaliate",
        description: `Whenever prey deals damage to the Bounty Hunter's ally, the Bounty Hunter gains +prey's difficulty tier% damage against that prey for 2 rounds. Stacks.`,
        groupId: 37,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Savour the Kill",
        description: `Whenever prey that is not being trailed is killed by an ally, the Bounty Hunter gains an extra turn with half of their MP and AP. The Bounty Hunter cannot attack during this extra turn.`,
        groupId: 37,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Trail and Shatter",
        description: `Hot on the Trail now has an unlimited range and reduces the target's armour by -(3 + PER bonus)% for 2 rounds.`,
        groupId: 37,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "We Got 'Em",
        description: `At the start of the Bounty Hunter's turn, they gain +2 MP for each ally who is adjacent to prey.`,
        groupId: 37,
        talentTypeId: 2,
        createdAt: new Date(),
      },

]
