export const executioner = [
  {
    name: "Executioner",
    description: "",
    groupId: 42,
    talentTypeId: 6,
    createdAt: new Date(),
  },
  {
    name: "Acute Pain",
    description: `Whenever an enemy suffers damage from a damage-over-time effect inflicted by the Executioner for the first time in combat, this damage is increased by +100%.`,
    groupId: 42,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "All-Encompassing Agony",
    description: `If an enemy suffering from any of the Executioner's damage-over-time effects is suffering from bleeding, burning (including effects inflicted by a pyromancer or a Navigator), and toxin (including effects inflicted by a biomancer) at the same time, all of these damage-over-time effects deal +30% more damage to that enemy.`,
    groupId: 42,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Anatomy Expert",
    description: `The maximum number of wounds for the Executioner depends on their Medicae instead of Toughness.`,
    groupId: 42,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Battle of Attrition",
    description: `At the start of each round, all enemies suffering from any damage-over-time effects inflicted by the Executioner have their incoming damage-over-time from any source increased by +20%. Stacks.`,
    groupId: 42,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Bleeding Stigmata",
    description: `Targets of Exsanguination are also immune to toxin and burning while suffering from bleeding.`,
    groupId: 42,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Bloody Trail",
    description: `While moving, all bleeding enemies leave a bloody trail on the ground which remains for 1 round. Moving through these bloodstained cells costs the Executioner 0 MP.`,
    groupId: 42,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Death in the Air",
    description: `Whenever an enemy suffering from toxin inflicted by the Executioner dies, all enemies in a 2-cell radius around that enemy suffer (INT bonus) levels of toxin.`,
    groupId: 42,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Death Warrant",
    description: `The level of the damage-over-time effect inflicted by the Executioner's Merciless Verdict is increased by +(maximum weapon damage / 5).`,
    groupId: 42,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Deep Laceration",
    description: `When using Scourging Strikes, the Executioner's melee critical hits inflict (3 x STR bonus) levels of bleeding on their targets instead of (2 x STR bonus) levels.`,
    groupId: 42,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Does it Hurt?",
    description: `All damage-over-time effects inflicted by the Executioner gain a 20% critical hit chance. This chance is increased by all bonuses to critical hit chance.`,
    groupId: 42,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Everlasting Agony",
    description: `The duration of negative effects inflicted by Pain Resonance is increased by +1 round, and the penalty to the corresponding resistance tests is increased to -(20 + medicae/5).`,
    groupId: 42,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Fragile Playthings",
    description: `The first instance of damage dealt by the Executioner's damage-over-time effects in a round reduces the inflicted enemy's armour by -(10 + INT bonus)% until the end of combat. This effect can be inflicted on multiple enemies per round, but only once per enemy. Stacks.`,
    groupId: 42,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Hardened Body",
    description: `Whenever the Executioner or their party members are suffering from any damage-over-time effects, these effects deal only 50% of their damage. Stacks multiplicatively (50% damage if there is one Executioner with this talent in the party, 25% damage if there are two Executioners with this talent in the party, etc.).`,
    groupId: 42,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Internal Bleeding",
    description: `When pushing an enemy, the Executioner also inflicts (Medicae/10) levels of bleeding on that enemy.`,
    groupId: 42,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Invigorating Screams",
    description: `Whenever an enemy in a 4-cell radius around the Executioner suffers damage from a damage-over-time effect, the Executioner regains +(TGH bonus/2) wounds.`,
    groupId: 42,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Maddening Flames",
    description: `At the start of their turn, an enemy suffering from burning inflicted by the Executioner must make a Willpower resistance test. If failed, burning is removed and the enemy falls prone until the start of their next turn.`,
    groupId: 42,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Master of Torture",
    description: `The Executioner deals +5% more damage to a target for each type of damage-over-time effect inflicted on that target.`,
    groupId: 42,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Perfect Anatomy",
    description: `The Executioner's armour is increased by +(5 + maximum wounds/20)%.`,
    groupId: 42,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Racking Weakness",
    description: `The damage dealt by the Executioner's damage-over-time effects is increased by (medicae / 20)% for every -10% penalty to armour suffered by the target from any source.`,
    groupId: 42,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Reprieve",
    description: `If the Executioner used Reckless Abandon in the previous round and, by the start of their turn, still has temporary wounds, they are healed for +(15% of maximum wounds) wounds.`,
    groupId: 42,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Revelling in Suffering",
    description: `Each adjacent creature counts as two for the purpose of calculating the bonuses granted by Gift of Torment.`,
    groupId: 42,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Sickening Pain",
    description: `Whenever a single instance of damage from any of the Executioner's damage-over-time effects deals damage equal to or more than 10% of the enemy's maximum wounds, that enemy gains +1 stack of fatigued.`,
    groupId: 42,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Sower of Distress",
    description: `Enemies suffering from any damage-over-time effect inflicted by the Executioner also suffer a -(5 + Medicae/20) penalty to their resistance tests.`,
    groupId: 42,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Tormenting Sprain",
    description: `Whenever an enemy suffering from any of the Executioner's damage-over-time effects dodges the Executioner's attack, all damage-over-time effects currently inflicted on that enemy now deal an additional +10% damage. Stacks.`,
    groupId: 42,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Unbearable Presence",
    description: `Targets of Terrifying Strike now make a Willpower resistance test with a -(10 + 2 x STR bonus) penalty. If failed, they provoke attacks of opportunity from the Executioner's allies during the forced movement.`,
    groupId: 42,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Vivisection",
    description: `The Executioner gains a +(Medicae/5) bonus to Lore (Xenos).`,
    groupId: 42,
    talentTypeId: 2,
    createdAt: new Date(),
  },
];
