export const exemplar = [
      {
        name: "Attention!",
        description: `After an ally takes an extra turn provided by the character, the ally gains +7% armour, +7% dodge, and +3 movement points until the end of combat. Does not stack.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Cataclysm",
        description: `All damage dealt by the character is increased by +3% until the end of combat for every new enemy damaged by them this combat.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Combat Meditation",
        description: `The character gains +15 Willpower as long as they have no ranged weapons equipped (staves do not count as ranged weapons).`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Contagion",
        description: `Whenever you apply blinded, slowed, fatigued, perplexed, or disturbed effects, one random enemy within 5 cells of the target also gains that effect for 1 round. The same happens if you inflict stunned or prone, but the random target makes a resistance test to avoid the effect.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Critical Velocity",
        description: `The character's critical hit chance and critical damage are increased by +5% of their dodge.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Crushing Assault",
        description: `The character's first melee attack each round deals an additional +2 damage for every cell between the character's current position and the spot where they started their turn. The distance is measured in a direct line, ignoring all terrain, with every second diagonal cell counting as two.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Deadly Aim",
        description: `If the character's dodge reduction is higher than the enemy's dodge, the character's damage against that enemy is increased by +1% for every 5% difference between the character's dodge reduction and the enemy's dodge.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Deathdealer",
        description: `Every round, after the character kills the first enemy, the character immediately makes an additional single attack against the closest enemy they can target with the same weapon if possible. This attack deals 30% base damage with a +10% bonus for every difficulty tier of the first killed enemy.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Degraded Defence",
        description: `Whenever the character deals damage to an enemy, that enemy suffers +1 stack of the degraded defence effect for every 6 damage that the character has dealt. Whenever an ally attacks that enemy, they deal additional damage equal to the number of degraded defence stacks. (Stacks cap 1000)`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Destroyer",
        description: `Every character's melee attack reduces the target's armour by STR% until the end of combat. This reduction is applied before damage is calculated. Stacks.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Disastrous Collision",
        description: `When targets pushed by the character collide with enemies or cover, both the target and the object they collide with suffer an additional +(2 x character's STR bonus) damage.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Eager for Battle",
        description: `During the first turn of combat, the character has +2 additional action points.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Eager Subordinates",
        description: `When allies take actions on extra turns given by the character, they deal +15% more damage.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Extermination",
        description: `Any damage the character deals is increased by +1 for every attack they have made this combat. Does not affect damage-over-time effects: bleeding, burning, or toxin.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Firebrand",
        description: `If an extra turn given by the character's abilities or talents grants MP, the target gains +4 additional MP; if AP - the target gains +1 additional AP.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Flagbearer",
        description: `Allies within 2 cells around the character deal +(3 + character's FEL bonus)% more damage and suffer -(3 + character's TGH bonus)% less damage. If multiple characters have this talent, the effect does not stack.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Fleshwounds",
        description: `At the start of the character's turn, they restore 10% of their maximum wounds. If the character has less than 20% of wounds left, they restore 20% of their maximum wounds instead.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Full Attention",
        description: `Targets that consider the character a priority target deal -40% less damage to the character's allies.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Grievous Wounds",
        description: `Enemies that have 0 deflection or 0% armour against the character's attacks suffer +10% additional damage from the character. If an enemy has both 0 deflection and 0% armour, those damage bonuses stack.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Know-It-All",
        description: `The character gains a +(2 + INT bonus / 2)% bonus to armour, armour penetration, dodge, dodge reduction, critical hit chance, critical damage, and parry chance.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Lethal Threat",
        description: `Enemies hit by the character with a melee attack must pass a Willpower resistance test or make the character their priority target until the start of the character's next turn.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Malign Influence",
        description: `Whenever an enemy fails a Willpower resistance test against the character, they suffer (2 x character's WP bonus) direct damage. On success the damage is doubled.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Martyrdom",
        description: `Whenever the character is attacked by an enemy, they gain momentum equal to the difficulty tier of the attacking creature.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Masterful Display",
        description: `When the character's single shots deal damage to targets other than their main target, they gain +5 Ballistic Skill until the end of combat.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Masterful Precision",
        description: `Deadeye shot deals an additional +(2 x PER bonus)% damage. The following ranged attack abilities gain Deadeye shot benefits: Bounty Hunter's Claim the Bounty, Master Tactician's Finish the Job, Assassin's Death Whisper, Assassin's Killing Edge, Assassin's Dispatch, Operative's Dismantling Attack, Bounty Hunter's Wild Hunt.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Out of My Way",
        description: `Whenever the character pushes an enemy, the character gains +4 MP. Those MP are added after the attack and allow the character to continue movement. Damage dealt by collisions from pushes is increased by +%.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Peak Condition",
        description: `The character gains a bonus to their Strength equal to 20% of their maximum wounds.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Perfection Under Fire",
        description: `The character gains +5 to all characteristics. This bonus is doubled when they have 25% wounds or less.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Pinpoint Accuracy",
        description: `The character ignores (BS bonus / 2) of the enemy's deflection (rounded down).`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Psychic Awakening (Biomancy)",
        description: `The character becomes an unsanctioned psyker and gains +1 psy rating.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Psychic Awakening (Divination)",
        description: `The character becomes an unsanctioned psyker and gains +1 psy rating.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Psychic Awakening (Pyromancy)",
        description: `The character becomes an unsanctioned psyker and gains +1 psy rating.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Psychic Awakening (Sanctic Powers)",
        description: `The character becomes an unsanctioned psyker and gains +1 psy rating.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Psychic Awakening (Telepathy)",
        description: `The character becomes an unsanctioned psyker and gains +1 psy rating.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Puncture",
        description: `If the character's armour penetration is higher than the enemy's armour, the character's critical hit chance against that enemy is increased by +2% for every 5% difference between the character's armour penetration and the enemy's armour.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Relentless",
        description: `Whenever the character is healed, they regain +(5 x character's TGH bonus)% more wounds.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Revenge",
        description: `Whenever the character loses wounds, their next melee attack gains +1 damage for every 2 wounds the character has lost. Stacks.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Shot Through",
        description: `The character's attacks gain an additional +(BS / 2)% overpenetration. Their overpenetration attacks cannot be dodged.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Steel Shell",
        description: `The character's deflection is doubled against single-target attacks.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Tipping Point",
        description: `The character's dodge reduction and armour penetration are increased by +10% of their critical hit chance.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Tough As Steel",
        description: `The character gains an additional 12 wounds. Those wounds are further increased by Toughness, increasing by +(10 x TGH bonus)%, in the same way as basic wounds.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Tricky Defence",
        description: `As long as the character wears light armour, their dodge is increased by half of the armour bonus of that armour.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Unbreakable Will",
        description: `The character gains a bonus to all resistance tests equal to +(5 x deflection).`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Unstoppable",
        description: `The character becomes immune to all effects that reduce their MP. They gain +(TGH bonus / 2) MP.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Vital Points",
        description: `Whenever the character scores a critical hit, they have a chance to increase their critical damage bonus by half. That chance is equal to (character's critical chance - 50)% (minimum of 0%).`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },

      {
        name: "Professional Know-How",
        description: `The wielder gains +shield block Weapon Skill and Ballistic Skill.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Strong Hand",
        description: `The wielder gains +5% block and deals +50% more damage with shield bash.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Invincibility",
        description: `The wielder gains (TGH / 3) deflection if a shield is in their current weapon set.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Adamantium Alloys",
        description: `The familiar's maximum wounds are increased by +(30 + overseer's tech use / 2).`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Autonomous Protection Algorithms",
        description: `In combat, the familiar gains +1 deflection for each cell between it and the overseer up to a maximum of (FEL).`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Emergency Algorithms",
        description: `Whenever the familiar's wounds drop below 20% for the first time in a round, the overseer's next ability has its cost reduced to 0 AP.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Mercy of the Omnissiah",
        description: `The familiar gains a (5 + overseer's level / 5)% chance to ignore any incoming damage.`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Poison Dispersal System",
        description: `If melee damage is dealt to the familiar, the attacker suffers toxic damage equal to (overseer's medicae / 4)% of the damage dealt (cannot be more than 100%).`,
        groupId: 35,
        talentTypeId: 2,
        createdAt: new Date(),
      },

]
