export const grandstrategist = [

      {
        name: "Adjusting Frontline",
        description: `If there are more enemies than allies in the Frontline area, all allies in the area gain +(3 + (Grand Strategist's INT + FEL bonus) / 2)% to parry and dodge. If there are more allies than enemies in the Frontline area, all allies in the area deal +(3 + (Grand Strategist's INT + FEL bonus) / 2)% damage.`,
        groupId: 39,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Crossfire Zone",
        description: `Using a stratagem on a Frontline area grants allies in the area +(10 + 2 x (Grand Strategist's INT + FEL bonus))% increased dodge against other allies' attacks.`,
        groupId: 39,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Diversion Zone",
        description: `Using a stratagem on a Rear area also makes the allies in that area the enemies' lowest priority targets for 1 round.`,
        groupId: 39,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Enduring Zone",
        description: `Using a stratagem on a Combat Tactics area grants all allies in the area +INT bonus deflection against the next melee hit they suffer.`,
        groupId: 39,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Personal Zone",
        description: `Allies, including the Grand Strategist, in the same Combat Tactics area with the Grand Strategist gain +(3 + INT bonus / 2) Perception and Agility.`,
        groupId: 39,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Point of Interest",
        description: `All Combat Tactics bonuses are increased by +((INT + FEL bonus) / 2)% if the area was not moved for 2 rounds.`,
        groupId: 39,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Redeployment",
        description: `Every time a Combat Tactics area is affected by a stratagem, all allies in that area gain +1 MP for the following turn. Stacks with itself.`,
        groupId: 39,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Blurred Locus",
        description: `After the use of Combat Locus Stratagem, one of the areas removed by Combat Locus Stratagem can be recreated immediately.`,
        groupId: 39,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Critical Zone",
        description: `Using a stratagem on a Backline area grants allies in the area +(3 + (Grand Strategist's INT + FEL bonus) / 2)% increased critical hit chance against enemies they are protected by cover from.`,
        groupId: 39,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Daunting Zone",
        description: `Willpower resistance tests forced by Overwhelming Stratagem are made with a -(5 + 2 X (INT + FEL bonus)) penalty.`,
        groupId: 39,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Disputed Zone",
        description: `Enemies in the same Combat Tactics area with the Grand Strategist suffer a -(3 + (Grand Strategist's INT + FEL bonus) / 2)% penalty to dodge and parry.`,
        groupId: 39,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Fire at Will",
        description: `If there are no enemies in the Backline area, the first attack in the turn made by every ally in that area costs -1 AP less.`,
        groupId: 39,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Fortress Zone",
        description: `Allies under the effects of Trenchline Stratagem will dodge area attacks without movement and are immune to all types of forced movement.`,
        groupId: 39,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Improvised Strategy",
        description: `At the start of combat, the Grand Strategist gains one random unknown stratagem and can use it until the end of combat for 0 AP.`,
        groupId: 39,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Inescapable Zone",
        description: `Re-rolls forced by Killzone Stratagem are made with a -15 penalty.`,
        groupId: 39,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Mobility Zone",
        description: `Using a stratagem on a Combat Tactics area grants all allies in the area the ability to move 1 cell without provoking attacks of opportunity.`,
        groupId: 39,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Opening Strategy",
        description: `The first stratagem used in a turn can be used a second time for 0 AP.`,
        groupId: 39,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Overcoming Zone",
        description: `Every time allies under the effect of Stronghold Stratagem should have suffered an injury, they gain +(INT + FEL bonus) temporary wounds instead.`,
        groupId: 39,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Personal Combat Zone",
        description: `Allies gain the ability to reposition the Combat Tactics area they are currently at the cost of 1 AP.`,
        groupId: 39,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Respite Zone",
        description: `All allies in the Rear area are healed by medikits for +(5 + Grand Strategist's INT + FEL bonus) more and gain the same amount of temporary wounds. Medikits used by allies in the Rear area cost -1 AP less.`,
        groupId: 39,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Sniping Zone",
        description: `Each ally in the Rear area gains +(3 + (Grand Strategist's INT + FEL bonus) / 2)% critical hit chance if there are no enemies in a 5-cell radius around the ally.`,
        groupId: 39,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Strategic Offensive",
        description: `Every enemy killed in the Frontline area increases all bonuses of Combat Tactics areas by +1 until the end of combat.`,
        groupId: 39,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Strategic Perfection",
        description: `Each time the Grand Strategist uses a stratagem, they gain a stack of the strategic perfection effect. At 6 stacks of strategic perfection, the next stratagem applies the benefits of all stratagems known by the Grand Strategist, then all the stacks are removed.`,
        groupId: 39,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Strongpoint",
        description: `Using a stratagem on a Combat Tactics area for the second time in a turn refunds 1 AP. This effect can be activated once per turn.`,
        groupId: 39,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Support Zone",
        description: `Using a stratagem on a Combat Tactics area grants the Grand Strategist the ability to use all Officer abilities on allies in the area regardless of distance.`,
        groupId: 39,
        talentTypeId: 2,
        createdAt: new Date(),
      },

]
