export const mastertactician = [

      {
        name: "Agas",
        description: `The Master Tactician begins combat with additional stacks of tactical advantage equal to the number of enemies.`,
        groupId: 38,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Brink of Death",
        description: `The Master Tactician deals +12% more damage to targets with less than 50% wounds and heals +20% more wounds for targets with less than 50% wounds.`,
        groupId: 38,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Hidden Advantage",
        description: `All the Master Tactician's abilities work as if the Master Tactician has FEL bonus more stacks of tactical advantage.`,
        groupId: 38,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Joint Offensive",
        description: `For every enemy hit by the Master Tactician's attack, the Master Tactician gains +1 stack of tactical advantage.`,
        groupId: 38,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Nerves of Steel",
        description: `Whenever the Master Tactician or their allies gain momentum, they gain +1 more. Whenever the Master Tactician or their allies lose momentum, they lose -1 less.`,
        groupId: 38,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Reliance",
        description: `Using Linchpin now spends only 1/4 of tactical advantage stacks instead of 1/2.`,
        groupId: 38,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Suppressive Fire",
        description: `All enemies hit by the Master Tactician have +10% higher chances of hitting a cover when shooting at the Master Tactician's allies behind a cover.`,
        groupId: 38,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Ally Coordination",
        description: `All allies have +25% dodge against attacks made by allies, deal -25% less damage to allies, and deal -50% less additional damage with critical hits against allies.`,
        groupId: 38,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Comfort in Conformity",
        description: `Whenever an ally grants the Master Tactician stacks of tactical advantage, that ally also heals 1 wound for every stack granted.`,
        groupId: 38,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Cost-Effective",
        description: `Grenades and medikits cost -1 less action point to use (minimum 0).`,
        groupId: 38,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Dawn of Victory",
        description: `Every critical hit scored by the Master Tactician grants them momentum equal to (resolve / 2). Works up to 3 times per turn.`,
        groupId: 38,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Heroic Inspiration",
        description: `The first ability the Master Tactician uses after the very first heroic act used in combat will cost 0 action points until the end of combat.`,
        groupId: 38,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "In the Hero's Footsteps",
        description: `Whenever the Master Tactician's ally uses a heroic act, the Master Tactician gains +5 Fellowship. Whenever their ally uses a desperate measure, the Master Tactician gains +5 Toughness. These bonuses stack and last until the end of combat.`,
        groupId: 38,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Logistical Superiority",
        description: `Whenever the Master Tactician or the Master Tactician's ally uses any consumable item (e.g., grenade, medikit, etc.) or reloads a weapon, the Master Tactician gains +2 stacks of tactical advantage.`,
        groupId: 38,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Perfect Finish",
        description: `Finish the Job gains +75% critical hit chance.`,
        groupId: 38,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Personal Involvement",
        description: `Every enemy killed by the Master Tactician increases the Master Tactician's resolve by +1 until the end of combat.`,
        groupId: 38,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Primary Objective",
        description: `Assign Objective also makes the target suffer +7% more damage from any source until the beginning of the Master Tactician's next turn.`,
        groupId: 38,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Salvation",
        description: `Using medikits on an ally under the effects of the Master Tactician's archetype abilities heals that target for additional wounds equal to (Master Tactician's FEL bonus + target's TGH bonus) and removes an extra injury without any tests.`,
        groupId: 38,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Stacking the Deck",
        description: `Whenever the Master Tactician spends tactical advantage stacks on abilities, the critical damage dealt by the Master Tactician increases by +1% for every stack spent until the end of the turn.`,
        groupId: 38,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Stand Resolute",
        description: `Whenever the Master Tactician heals an ally, that ally gains +1 resolve until the end of combat. This effect stacks up to a maximum of +FEL bonus.`,
        groupId: 38,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Stronghold",
        description: `Strongpoint also grants half the amount of temporary wounds to the ally closest to the target.`,
        groupId: 38,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Support the Advance",
        description: `At the beginning of the Master Tactician's turn, if their momentum is higher than 125, the first burst attack or area attack used by the Master Tactician this turn costs -1 less AP (minimum 0).`,
        groupId: 38,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Tactical Respite",
        description: `Whenever the Master Tactician reloads a weapon, all allies within a 3-cell radius around the Master Tactician also reload their weapons.`,
        groupId: 38,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Undisputed Advantage",
        description: `Press the Advantage ignores cover and dodge.`,
        groupId: 38,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Unwavering Motivation",
        description: `The target of Inspire gains +1 additional damage for every 10 stacks of tactical advantage until the beginning of the Master Tactician's next turn.`,
        groupId: 38,
        talentTypeId: 2,
        createdAt: new Date(),
      },
]
