export const navigator = [


  {
        name: "Tonicity",
        description: `Navigator path powers deal +1 additional damage for every 5 bonus characteristic of the Navigator's currently equipped staff. Casting, infusing, and devastating count as characteristics for this talent.`,
        groupId: 43,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Eye of Oblivion",
        description: `Every enemy the Navigator has in their line of sight has its dodge and hit chance reduced by -(Navigator's PER bonus).`,
        groupId: 43,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Strange Vitality",
        description: `The Navigator heals WP bonus wounds at the beginning of every turn and gains +1 additional wound for every Navigator talent taken. The healing increases by +1 for every creature killed between the Navigator's turns.`,
        groupId: 43,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Perilous Ways",
        description: `Enemies moved by the Navigator's abilities suffer 1 + WP bonus/2 damage at the end of movement. This damage is increased by +1 for every cell the enemy moves.`,
        groupId: 43,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "The Course Untravelled",
        description: `Whenever the Navigator uses a Navigator power that hasn't been used this combat, the Navigator gains +2 Perception until the end of combat.`,
        groupId: 43,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Guide of Souls",
        description: `The Navigator starts all turns, including extra turns, with +3 additional movement points. The first ally targeted each turn by the Navigator with a single-target ability gains the same amount of additional movement points at the start of their next turn.`,
        groupId: 43,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Under My Protection",
        description: `Allies targeted by the Navigator's abilities gain +5 to all resistance tests against warp effects until the end of combat. The effect stacks with every applied Navigator ability.`,
        groupId: 43,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Veil of Protection",
        description: `Allies targeted by the Navigator's power gain +10% armour. This additional armour is reduced by the amount of veil degradation (to a minimum of +0%) and increased by the infusing of the currently equipped Navigator's staff.`,
        groupId: 43,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Blood Augury",
        description: `Enemies damaged by the Navigator suffer +(5 + Navigator's PER bonus)% additional damage from warp damage. The bonus damage stacks for each hit.`,
        groupId: 43,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Ebb and Flow",
        description: `Every even (second, fourth, etc.) turn, the Navigator gains an additional action point. Every odd turn (first, third, etc.) the Navigator gains +20 Perception.`,
        groupId: 43,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Mind Over Matter",
        description: `The Navigator uses Willpower for resistance tests if it is higher than the base characteristic for such test. If the Navigator's Willpower is higher than their Toughness, the Navigator's wounds are calculated according to their Willpower.`,
        groupId: 43,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Unnatural Allure",
        description: `The Navigator gains +5 to Fellowship and an additional +1 to Fellowship for every Navigator talent and/or Navigator power taken.`,
        groupId: 43,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Threads and Faults",
        description: `Whenever an enemy fails a resistance test against a Navigator's power, attacks against them gain +(20 + 2 x PER bonus)% critical hit chance. The effect stacks but is reset by a critical hit.`,
        groupId: 43,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Open to the Warp",
        description: `Enemies affected by the Navigator's abilities suffer a stacking -10 penalty to the next resistance test from the Navigator's powers. The penalty is lost after such a test is made.`,
        groupId: 43,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Mastery of Time",
        description: `Whenever a Navigator's ally in combat gains an extra turn, the Navigator gains a stacking +5 bonus to Willpower until the end of combat (up to 5 times).`,
        groupId: 43,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Pass Unscathed",
        description: `If the Navigator's Perception is higher than their Agility, their dodge is calculated using Perception instead.`,
        groupId: 43,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Undam the Sea of Souls",
        description: `While under the effect of any Navigator power, enemies have their armour reduced by -(5 + Navigator's WP bonus). This reduction is increased by the devastating parameter of the Navigator's staff but does not stack.`,
        groupId: 43,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Unblinking Stare",
        description: `Until the end of combat, enemies damaged by the Navigator suffer an additional +PER bonus damage from all attacks of opportunity and cannot dodge them.`,
        groupId: 43,
        talentTypeId: 2,
        createdAt: new Date(),
      },
      {
        name: "Stable Routes",
        description: `Whenever the Navigator uses a Navigator ability, veil degradation is reduced by -1.`,
        groupId: 43,
        talentTypeId: 2,
        createdAt: new Date(),
      },
]
