export const operative = [
  {
    name: "Analyse Enemies",
    description: `The Operative targets one enemy within line of sight. That target immediately gains +(1 + INT bonus / 2) exploits.
Expose Weakness: The Operative removes all exploits from the target to decrease the target's dodge, parry, and armour by -(15 + exploits stacks x PER bonus)% until the start of the Operative's next turn.
If this ability reduces the target's armour to 0, the Operative only removes only half of the exploits from the target.`,
    groupId: 31,
    talentTypeId: 1,
    createdAt: new Date(),
  },
  {
    name: "Joint Analysis	",
    description: `Until the Operative's next turn, their allies' attacks also remove exploits and deal +INT bonus more damage.`,
    groupId: 31,
    talentTypeId: 1,
    createdAt: new Date(),
  },
  {
    name: "Precise Attack	",
    description: `For the next attack against a target affected by an exploit, that target's cover fficiency will be reduced by -(15 + (PER bonus/3 x stacks of exploit))%. This attack will have +(15 + PER bonus/3- x stacks of exploit)% hit chance.
`,
    groupId: 31,
    talentTypeId: 1,
    createdAt: new Date(),
  },
  {
    name: "Intimidation",
    description: `The Operative's next non-area attack inflicts the intimidated effect on the first target hit by the attack and all enemies in a 5-cell radius around that target.
The damage dealt by intimidated enemies is reduced by -(5 + PER bonus/2)% until the Operative's next turn. This negative effect is doubled for enemies with less than (3 x INT bonus)% armour.`,
    groupId: 31,
    talentTypeId: 1,
    createdAt: new Date(),
  },
  {
    name: "Perfect Spot",
    description: `While in cover, the Operative gains +25% cover efficiency, +15 Perception, and +15 Ballistic Skill. This effect lasts until the Operative moves. Does not stack.
`,
    groupId: 31,
    talentTypeId: 1,
    createdAt: new Date(),
  },
  {
    name: "Tactical Knowledge",
    description: `he Operative removes -1 exploit from each enemy in a 5-cell radius around a point within 10 cells from the Operative. If there is only one enemy in the area, the Operative removes all exploit stacks from that enemy.
All allies gain +(number of removed exploits)% armour until the end of combat. If 4 or more exploits are removed, the Operative gains +(2 x number of removed exploits)% damage until the end of combat.`,
    groupId: 31,
    talentTypeId: 1,
    createdAt: new Date(),
  },

  ///
  {
    name: "Operator",
    description: ``,
    groupId: 31,
    talentTypeId: 5,
    createdAt: new Date(),
  },
  {
    name: "Operator I",
    description: ``,
    groupId: 31,
    talentTypeId: 5,
    createdAt: new Date(),
  },
  {
    name: "Operator II",
    description: ``,
    groupId: 31,
    talentTypeId: 5,
    createdAt: new Date(),
  },
  {
    name: "Operator III",
    description: ``,
    groupId: 31,
    talentTypeId: 5,
    createdAt: new Date(),
  },
  {
    name: "Operator IV",
    description: ``,
    groupId: 31,
    talentTypeId: 5,
    createdAt: new Date(),
  },
  ///

  {
    name: "Fresh Target",
    description: `Whenever the Operative attacks an enemy that is at full wounds, that attack deals +(10 + PER bonus)% more damage to that enemy.`,
    groupId: 31,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Instant Exposure",
    description: `Expose Weakness costs 0 AP.`,
    groupId: 31,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Tide of Excellence",
    description: `Whenever the Operative triggers an exploit on an enemy, the Operative gains +1 damage and +2% armour penetration until the end of combat. Stacks.`,
    groupId: 31,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Weak Body, Weak Soul",
    description: `Expose Weakness also reduces enemies' Toughness and Willpower by -(3 x INT bonus) for 1 round.`,
    groupId: 31,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Ballistics Calculation",
    description: `If the Operative attacks a target affected by an exploit from a distance of (15 - PER bonus) cells or farther, that attack deals +15% damage.`,
    groupId: 31,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Combat Insight",
    description: `While the Operative's Perception bonus is 10 or higher, they gain +1 AP and ignore enemies' deflection.`,
    groupId: 31,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Comprehensive Analysis",
    description: `If the target of Analyse Enemies has 2 or more exploits, that target suffers +1 additional exploit.`,
    groupId: 31,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Continuous Analysis",
    description: `At the start of the Operative's turn, the enemy with the largest number of exploits receives an additional exploit stack. If two or more enemies are tied for the largest number of exploit stacks, one of those enemies is chosen at random.`,
    groupId: 31,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Covert Protocol",
    description: `While the Operative is in half cover, their cover efficiency is increased by +15%. This bonus is doubled if the Operative has not moved during their turn.`,
    groupId: 31,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Improved Tactics",
    description: `Tactical Knowledge requires 3 exploits instead of 4. The Operative's damage is increased by +INT bonus.`,
    groupId: 31,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Inflict Despair",
    description: `Whenever the Operative hits an enemy that is affected by both an exploit and Expose Weakness, that enemy loses -3 MP and their damage is reduced by -20% on their next turn.`,
    groupId: 31,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Informed Hit",
    description: `If the Operative uses Precise Attack on a target affected by (10 - INT bonus) or more exploits and scores a hit, that hit becomes a critical hit.`,
    groupId: 31,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Insightful Precision",
    description: `Precise Attack grants the Operative a bonus to Perception equal to (number of exploits removed / 2) (minimum 1).`,
    groupId: 31,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Joint Offensive",
    description: `The Operative's allies gain +Operative's INT bonus / 2 hit chance and critical hit chance while attacking targets affected by exploits.`,
    groupId: 31,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Offensive Pattern Prediction",
    description: `The Operative suffers -(5 + INT bonus)% less damage from enemies affected by exploits.`,
    groupId: 31,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Passive Learning",
    description: `On their first turn in combat, the Operative randomly distributes the same number of exploits as when using Analyse Enemies among all enemies in a 10-cell radius around the Operative. At the start of each of the Operative's subsequent turns, they distribute half as many exploits (half the base amount) among all enemies in a 2-cell radius around the Operative.`,
    groupId: 31,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Reactive Study",
    description: `If an enemy affected by an exploit within 5 cells from the Operative attacks the Operative or their ally, that enemy suffers +1 additional exploit.`,
    groupId: 31,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Sharpshooter",
    description: `If the Operative has not moved this turn, they gain +PER bonus Ballistic Skill and +(INT bonus / 2) damage for every 5 cells between them and the target.`,
    groupId: 31,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Sniper Expertise",
    description: `Perfect Spot additionally grants the Operative +(5 + PER bonus)% armour penetration against enemies that are 7 cells away or farther.`,
    groupId: 31,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Terrifying Presence",
    description: `If Intimidation kills the target, the damage of all other enemies in the area of Intimidation is reduced by an additional -(4 x INT bonus)%.`,
    groupId: 31,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Uncanny Sight",
    description: `The Operative inflicts an exploit even on enemies which are out of the Operative's line of sight at the start of the turn.`,
    groupId: 31,
    talentTypeId: 2,
    createdAt: new Date(),
  },
]
