export const origins = [
  {
    name: "Death World",
    description: "Once per combat, when the wounds of a death world character drop below 30%, they gain +20% of their maximum wounds as temporary wounds. Death world characters also gain a +20% bonus to dodge and armour while they have at least 1 temporary wound from any a source.",
    groupId: 28,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Brutal Hunter",
    description: "Death world characters gain +15% critical hit chance against targets with the bleeding effect or with 50% or less of their maximum wounds",
    groupId: 28,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Trusty Weapons",
    description: "Death world characters gain +10% to critical hit chance for axes, hammers, and las weapons.",
    groupId: 28,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Wounded Beast",
    description: "Every Injury increases the death world character's Agility and Willpower by +5. Every trauma counts as 3 Injuries.",
    groupId: 28,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Lifetime of scars",
    description: "Death World characters take TGH bonus less damage from flame, toxic damage, and bleeding effects.",
    groupId: 28,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Tenacity",
    description: "Once per combat, when a death world character is suffering from the stunned, blinded, or immobilised condition, this condition is ignored, and they instead gain +20% temporary wounds to their maximum wounds.",
    groupId: 28,
    talentTypeId: 2,
    createdAt: new Date(),
  },

  // Voidborn Talents
  {
    name: "Voidborn",
    description: `A voidborn character can reroll any failed attack, dodge, parry, characteristic, or skill test with a 20% chance of success. This chance cannot be greater than the base success chance of the roll.
  Additionally, any enemy dodge or parry against a voidborn character has a 20% chance to fail after a successful roll.`,
    groupId: 22,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Bloody Mess",
    description: `Any time a voidborn character scores a critical hit, there is a 10% chance to double the damage.`,
    groupId: 22,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Contagious Luck",
    description: `Using a non-damaging ability on an ally grants that ally the ability to reroll any failed attack, dodge, parry, characteristic, or skill test with a 20% chance of success for 1 round. This chance cannot be greater than the base success chance of
  the roll. Using a non-damaging ability on an enemy grants them a 20% chance to fail a successful dodge or parry test against any character for 1 round.`,
    groupId: 22,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Just a flesh wound",
    description: `The voidborn character has a 20% chance to survive after suffering lethal damage, surviving with 1 wound.`,
    groupId: 22,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Jinx",
    description: `While a voidborn character has more than 50% wounds, all chances of all creatures (including enemies) in a 3-cell radius are increased by +10%. While a voidborn character has less than 50% wounds, all chances of all creatures
  (including enemies) in a 3-cell radius are decreased by -10%.`,
    groupId: 22,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Be Smart	",
    description: `Any time an ability or talent uses the Fellowship bonus, a voidborn character can instead use the Intelligence bonus, if it is higher. Additionally, voidborn characters can always upgrade Intelligence even if their archetype does not allow it.
  `,
    groupId: 22,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Hive World",
    description: `Hive world characters gain +((1 + FEL bonus) / 2) resolve if there are 3 or more creatures (allies or enemies) in a 3-cell radius. They suffer a -2 penalty to resolve with no creatures around.`,
    groupId: 21,
    talentTypeId: 3,
    createdAt: new Date(),
  },
  {
    name: "Comradery",
    description: `Hive world characters can pass Willpower resistance tests using their Fellowship value instead, if the character's Fellowship is higher.`,
    groupId: 21,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Outnumber",
    description: `If a hive world character has melee superiority against the enemy, the effect is increased by +10. If an enemy has melee superiority against a hive world character, the effect is decreased by -10. Melee Superiority: in melee combat, any target surrounded by more allies than enemies receives a +10 WS bonus for each additional ally.`,
    groupId: 22,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Weapon Personalisation",
    description: `All ranged weapons dealing physical damage have +1 damage, +5% armour penetration, +1 rate of fire, and -5 to recoil.`,
    groupId: 21,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Helping Hand",
    description: `If a hive world character starts their turn adjacent to an ally, that hive world character gains +2 MP. If they end their turn adjacent to allies, those allies gain +2 MP on their next turn.`,
    groupId: 21,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Fresh Start",
    description: `Hive world characters gain a +50% bonus to dodge against the first attack of opportunity every round.`,
    groupId: 21,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Forge World",
    description: `Choose one: Subskin Armour, grants 5 + (2 x TGH)% armour — Locomotion System, grants AGI/2 MP and 2 x AGI% dodge — Analytics System, grants 10 + INT% critical hit chance.`,
    groupId: 19,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Pinnacle of Weaponry",
    description: `The first attack in combat with any plasma, melta, or power weapon deals additional damage equal to INT bonus. For the remainder of combat, the bonus damage is decreased to (INT bonus / 2).`,
    groupId: 19,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Fires of the Forge",
    description: `Forge world characters gain +TGH bonus deflection against burning effects and flame weapons.`,
    groupId: 19,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Steel of the Forge",
    description: `While wearing heavy armour, forge world characters gain +1 MP, +1 deflection, and cannot fall prone.`,
    groupId: 19,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Persistence of the Forge",
    description: `Forge world characters gain a stacking +10% bonus to hit chance and dodge reduction against any target they hit with a single-target attack. Successful critical hits from single-target attacks increase the hit chance and dodge reduction by +20%.`,
    groupId: 19,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Calculated Relation",
    description: `Forge world characters can use Persuasion, Coercion, and Commerce based on Intelligence instead of Fellowship.`,
    groupId: 18,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Imperial World",
    description: `Imperial world characters can select any characteristic (except Weapon Skill or Ballistic Skill) and add a +10 bonus.`,
    groupId: 18,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Ready to Serve",
    description: `When an Imperial world character is affected by an ally's non-damaging ability or affects an ally with such an ability, their resolve is increased by (FEL bonus / 2) for 1 round.`,
    groupId: 18,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Better to die for the Emperor",
    description: `While under 40% wounds, Imperial world characters gain a +10 bonus to all characteristics and +2 to resolve.`,
    groupId: 18,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Doing My Part",
    description: `If no other character in the current party is from an Imperial world, the first use of any of the character's archetype abilities costs -1 AP less.`,
    groupId: 18,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Know No Heresy",
    description: `Imperial world characters gain +10% critical hit chance and +10% armour against xenos or daemonic creatures. Their allies gain half the bonuses. However, Imperial world characters' Lore (Xenos) and Lore (Warp) are always 0.`,
    groupId: 18,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Stronger Together",
    description: `All allies, excluding xenos, in the current party gain +5 to the same characteristic as was chosen for Humanity's Finest.`,
    groupId: 18,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Fortress World",
    description: `Each time a fortress world character kills an enemy, they gain +10 stacks of never stop shooting. At the start of their turn, there is a (stacks of never stop shooting)% chance that the first attack this round will cost 0 AP and will not
  count toward the attack limit per round. If this effect triggers, all the stacks are lost.`,
    groupId: 20,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Combat Addict",
    description: `Fortress world characters gain +7 to Ballistic Skill, Perception, and Willpower while in combat. Yet while out of combat, their Intelligence, Fellowship, Perception, and Willpower are decreased by -7.`,
    groupId: 20,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Hail of Steel",
    description: `Each round fortress world characters gain a stacking +1% bonus to dodge against ranged attacks for each shot they made during this round. Also, the burst attack grants an additional +10 stacks of never stop shooting.`,
    groupId: 20,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Familiar Kickback",
    description: `At the end of their turn, fortress world characters gain stacks of never stop shooting equal to (half the minimal damage of the most damaging ranged weapon they used this round).`,
    groupId: 20,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Spare Magazine",
    description: `Fortress world characters' first reload in combat costs 0 AP. Reloading a weapon grants an additional +10 stacks of never stop shooting.`,
    groupId: 20,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Never Stop Believing",
    description: `When all stacks of never stop shooting should be lost, they become (WP / 2) number of stacks instead. Additionally, a fortress world character may upgrade their Willpower characteristic even if their
  current archetypes do not allow it.`,
    groupId: 20,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Astra Militarum Commander",
    description: `When used for 1 round the commander and their allies do not suffer damage from allied attacks and deal (20+2xFEL)% more damage to enemies that were attacked by them since this ability activation. The effect does not stack. Can only be used once per combat.`,
    groupId: 1,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Suppression Fire!",
    description: `Whilst Regimental Tactics effect lasts, the commander and their allies' weapon attacks gain +20% dodge reduction, parry reduction, block reduction and cover penetration against targets that have been attacked by allies this combat.`,
    groupId: 1,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Field of Fire",
    description: `While the Astra Militarum commander is under the Regimental Tactics effect, all their allies gain +5% to rate of fire for every attack they have made since the start of this effect.`,
    groupId: 1,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Fix Bayonets!",
    description: `Two-handed las weapons equipped by the commander or allies gain a bayonet strike single melee attack that costs 1 AP. This attack deals the same damage as the las weapon and does not count to attack limit.`,
    groupId: 1,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Unflinching Heroism",
    description: `Whenever the commander or their allies performs a heroic act, all the commander's characteristics are increased by +7 until the end of combat.`,
    groupId: 1,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Trench Warfare",
    description: `While the commander is in partial cover, their las weapon's rate of fire is increased by 20% and 40% when in full cover.`,
    groupId: 21,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Commissar",
    description: `Commissar shoots an allied character with the pistol in their primary hand, dealing 100+Coercion% of weapon damage. This shot ignores armour and deflection. Always hits. Ally gains At All Costs effect; if the ally falls unconscious the effect is applied to all other allies besides the commissar. Grants (2xFEL)% damage, (2xFEL)% dodge and parry and (Commissar's Coercion / 10) to all characteristics. Iconic Sidearm: Shots with pistol in primary hand deal (2x Commissar's BS bonus)% more damage, gain 15% critical hit chance, and (2x Commissar FEL bonus)% dodge reduction.`,
    groupId: 2,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "One for the enemies, two for the traitors",
    description: `The effect of the iconic sidearm is now active when a pistol is equipped in either hand (shots with pistol in their primary hand deal FEL% more damage, gain 15% critical chance and dodge reduction).`,
    groupId: 2,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Let them know fear!",
    description: `While the Commissar is adjacent to an enemy, all their allies gain +(1 + Commissar's FEL bonus / 2) resolve; if there are no creatures in a 2-cell radius the commissar gains this bonus resolve.`,
    groupId: 2,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Motivation",
    description: `The commissar's MP is increased by (1 + character level \\ 10). All allies starting their turn in a 2-cell radius around the commissar also gain (1 + character level \\ 10) MP. Once per round, after the commissar performs an attack with a pistol, they gain (FEL \\ 2) MP. Does not stack.`,
    groupId: 2,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Summary Execution",
    description: `When the commissar uses At All Costs! while shooting from behind, the bonuses granted by the effect are doubled.`,
    groupId: 2,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "For the emperor!",
    description: `If an ally remains in combat after being attacked with the ability At All Costs and then kills an enemy while under the effect, they will regain 30% of the wounds lost due to At All Costs as temporary wounds.`,
    groupId: 2,
    talentTypeId: 2,
    createdAt: new Date(),
  },

  {
    name: "Crime Lord",
    description: `At the start of combat, the crime lord gains +INT bonus stacks of the Sure-Fire Plan effect. Activation of this ability consumes 1 stack and makes the next action stronger depending on the type of action: if the crime lord attacks, they deal +(10 + PER bonus)% more damage; if they move, they gain +(10 + PER bonus)% dodge and parry until the start of their next turn; if they use a non-damaging ability on an enemy, that enemy suffers a -(10 + INT bonus)% penalty to damage for one round. Can be used multiple times per turn.`,
    groupId: 3,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Killing Plan",
    description: `The bonus damage of Sure-Fire Plan is increased by +(2 x WS bonus)%. Killing at least one enemy with an attack restores 1 stack of Sure-Fire Plan.`,
    groupId: 3,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Escape Plan",
    description: `The bonus to dodge and parry from Sure-Fire Plan are increased by +(2 x AGI bonus)%. Dodging or parrying at least one attack by the start of the next round restores 1 stack of Sure-Fire Plan.`,
    groupId: 3,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Disorienting Plan",
    description: `An enemy affected by Sure-Fire Plan also suffers a -(10 + 2 x PER bonus)% penalty to dodge and parry.`,
    groupId: 3,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Contingency Plan",
    description: `If at the start of a turn the crime lord has no stacks of Sure-Fire Plan, they gain +1 stack.`,
    groupId: 3,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "The Last Plan",
    description: `Once per combat, if the crime lord has at least 1 stack of Sure-Fire Plan, they do not die from lethal damage. Instead, they heal (5 x Sure-Fire Plan stacks)% of maximum wounds, lose a stack, and can no longer gain Sure-Fire Plan stacks.`,
    groupId: 3,
    talentTypeId: 2,
    createdAt: new Date(),
  },

  {
    name: "Ministorum Priest",
    description: `Grants 2x number of Steal stacks momentum. Then the priest gains WP bonus stacks of Zeal. Does not provoke attacks of opportunity. Whilst in combat priest gains +Willpower. Attacks with bolter, flamer, chain, melta or power deal per enemy attacked for the first time in combat. They gain +2 stacks of Zeal for xenos and daemons killed in combat. Unshakable Faith: in combat priest gains (2 x (STR, TGH, AGI, PER)) Willpower.`,
    groupId: 4,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Litany of Purification",
    description: `Whenever the character uses War Hymn or Furious Recital, each daemon and xenos in a 5-cell radius suffers 5 x Zeal stacks direct damage and +1 stack of Perplexed.`,
    groupId: 4,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Litany of Hatred",
    description: `Whenever the priest uses War Hymn, for 1 round, the priest and allies in a 5-cell radius deal + (number of Zeal stacks / 2) more weapon damage. This is doubled against daemons, psykers and xenos.`,
    groupId: 4,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Tenets of Retribution",
    description: `The priest deals +WP/3 more damage and WP% more critical damage with bolt weapons. Base melta weapon and flamer damage is increased by WP bonus%. These bonuses are doubled against daemons, psykers and xenos.`,
    groupId: 4,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "The Emperor Protects",
    description: `Priest's maximum wounds are increased by Willpower bonus.`,
    groupId: 4,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Flensing Faith",
    description: `Priest gains WP bonus% armour penetration with chain and power weapons. Critical hits scored with such weapons inflict WP bonus/2 levels of burning. Bonuses doubled vs xenos, daemons and psykers.`,
    groupId: 4,
    talentTypeId: 2,
    createdAt: new Date(),
  },
    {
    name: "Navy Officer",
    description: `For 1 round, the Navy officer and their allies in a 5-cell radius gain +2 deflection for each Archetype taken by the Navy officer. They also cannot be forcefully moved or overpenetrated. Can only be used once. +1 charge when the navy officer drops below 50% for the first time in combat.`,
    groupId: 5,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Stentorian Voice",
    description: `Enemies in a 5-cell radius around the navy officer whilst Brace effect lasts suffer -(10 x number of archetypes) Weapon Skill and Ballistic Skill.`,
    groupId: 5,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Evasive Manoeuvres",
    description: `All allies affected by Braced effect or by the navy officer non-attacking archetype abilities gain (10 + 2 x PER)% dodge for 1 round. Officer and braced allies do not provoke attacks of opportunity.`,
    groupId: 5,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Fleet Combat Training",
    description: `When the navy officer scores a critical hit or successfully parries an attack with their primary melee weapon, they immediately make an attack with their secondary weapon against the same enemy.`,
    groupId: 5,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Get off Me!",
    description: `Brace for Impact! also allows the Navy Officer to use any ranged weapon in threatened areas, knocks enemies prone, and pushes them 1 cell away during the effect.`,
    groupId: 5,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Get Into Cover!",
    description: `All allies affected by Brace for Impact! gain an extra turn with 0 AP and 3 MP and increase their cover efficiency by +20% for 1 round.`,
    groupId: 5,
    talentTypeId: 2,
    createdAt: new Date(),
  },

  {
    name: "Noble",
    description: `The noble assigns one ally who will become their servant until the end of combat. Any time the noble's abilities affect the servant, the servant gains +5 to all characteristics until the start of the noble's next turn. Any time the servant attacks a target that the noble dealt damage to last turn, the servant gains +(10 + noble's FEL bonus)% critical hit chance against that target. Can only be used once per combat.`,
    groupId: 6,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "You. Do Something.",
    description: `If a noble uses an ability on their servant, the servant gains +1 AP next turn. Does not stack with itself.`,
    groupId: 30,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "You. Protect Me.",
    description: `If the noble and the servant are adjacent at the start of the noble's turn, they both gain temporary wounds equal to servant's TGH bonus or noble's FEL bonus depending on which is higher.`,
    groupId: 6,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "You. Go On.",
    description: `The noble's servant gains +2 movement points every turn.`,
    groupId: 6,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "You. Kill It.",
    description: `If the servant kills the target that the noble dealt damage to last turn, the noble gains +1 AP next turn.`,
    groupId: 6,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "You. You Are Next.",
    description: `If the servant has less than 30% maximum wounds, the noble can use You. Serve Me. once more in battle, designating a new servant and removing the effect from the previous one. The noble cannot designate a character who already was their servant this combat.`,
    groupId: 6,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Sanctioned Psyker",
    description: `Sanctioned Psykers have reduced 20% chances to trigger psychic phenomena.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Psyker Minoris",
    description: `Each level of psy rating provides the psyker access to new psychic powers. It also strengthens damaging psychic powers. (Minoris level).`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Psyker Majoris",
    description: `Each level of psy rating provides the psyker access to new psychic powers. It also strengthens damaging psychic powers. (Majoris level).`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Psyker Terminus",
    description: `Each level of psy rating provides the psyker access to new psychic powers. It also strengthens damaging psychic powers. (Terminus level).`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Psyker Extremis",
    description: `Each level of psy rating provides the psyker access to new psychic powers. It also strengthens damaging psychic powers. (Extremis level).`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Still Mind",
    description: `The psyker's resolve is increased by +(WP bonus / 2) while veil degradation is 10 or lower.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Inscribed Soul",
    description: `The psyker gains the Inscribed Soul ability. It costs no AP but deals direct damage to the psyker equal to 25% of the psyker's maximum wounds. The next psychic power used after this ability will not trigger psychic phenomena or perils of the warp and will not degrade the veil.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Sacred Rituals",
    description: `Psychic powers have a 25% chance to regain AP spent on psychic powers when veil degradation is 10 or lower.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Blade of Light",
    description: `Force weapon attacks deal +psy rating more damage and have +(5 x psy rating)% more armour penetration.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Enforce Reality",
    description: `Usage of a heroic act by the psyker decreases veil degradation by INT bonus.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Psychic Barrage",
    description: `Whenever the psyker uses a damaging psychic power on targets that are 6 cells or farther from the psyker, the targets suffer an additional +BS bonus damage.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Second Sight",
    description: `The psyker's psychic powers that have a range of 2 cells or more have their range increased by +PER bonus.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Stabilising Factor",
    description: `The first psychic power used each turn increases veil degradation by 2 points less. If this talent reduces the effect on veil degradation to less than 0, veil degradation is instead decreased by 1.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Subtle Manipulation",
    description: `The psyker can use a damaging psychic power while being threatened by enemies in melee range without provoking attacks of opportunity. Non-damaging psychic powers do not provoke attacks of opportunity even without this talent.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Obscured Threat",
    description: `While the psyker is not in the target's line of sight, or the psyker is in cover, all resistance tests of the target suffer a -(4 x psy rating) penalty.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Psyker - Biomancer",
    description: `The target gains +(10 + 4 × psyker’s psy rating) Strength and Toughness until the end of combat.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Adrenaline Surge",
    description: `On the first turn of every combat, all psychic powers of the biomancy discipline cost -1 action point.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Biophysical Distortion",
    description: `All the psyker's attacks, including damaging psychic powers, now poison enemies. This poison deals (4 x psy rating) damage every turn.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Sanguine Siphon",
    description: `Every time the psyker deals damage, they gain +1 stack of the Sanguine Siphon effect. If that damage was dealt to a target adjacent to the psyker, they gain +2 stacks instead. When the psyker suffers lethal damage, the stacks of Sanguine Siphon are removed to reduce this damage by -1 for each stack, until either all stacks are removed or the damage is no longer lethal.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Confer Immunity",
    description: `Whenever the psyker is healed or heals any ally, if the character being healed is already at full wounds, that character instead gains temporary wounds equal to the healing. These temporary wounds do not stack.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Corpus Conversion",
    description: `When an enemy adjacent to an ally dies, that ally gains a stacking Corpus Conversion effect. If multiple allies are adjacent to the dead enemy, one is selected at random. The psyker's next psychic power that targets only the target with Corpus Conversion will work as if the psyker's psy rating is +2 higher, will not damage the veil, will not trigger psychic phenomena or perils of the warp, and will remove -1 stack of Corpus Conversion from the target. (Note: appears to be bugged and may add +2 psy rating on every psyker buff).`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Pulse of Life",
    description: `Whenever the psyker heals themselves or another character with a psychic power or an effect applied by a psychic power, this healing can critically heal with a chance of (5 + 2 x WP bonus)%. This critical heal chance is increased by all effects that increase critical hit chance, and the amount healed is increased by the same value as critical damage.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Warp Saturation",
    description: `When the psyker's allies or the psyker themselves are under the effects of the psychic powers, they gain +5 Toughness for each such effect.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Deterioration",
    description: `Whenever an effect applied by the psyker increases the damage suffered by a target, this effect is increased by half (for example, a 20% increase turns into a 30% increase).`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },

  {
    name: "Psyker - Diviner",
    description: `The psyker increases the target's dodge and parry by +(3 + psyker’s PER bonus + 3 × psy rating)% until the end of combat.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Edge of Fate",
    description: `At the beginning of every combat, the psyker's allies gain +15% critical hit chance. The first critical hit removes this effect.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Fatebringer",
    description: `Allies under the effect of at least one psychic power gain an additional +(5 + 2 x psyker's psy rating)% armour penetration.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Flawless Plan",
    description: `Every 9th successful dodge and/or parry by the psyker and their allies combined grants the psyker +2 additional AP on the next turn.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Predicted Downfall",
    description: `The first dodge attempt of every enemy in combat suffers a -(7 x psyker's psy rating)% penalty.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Unnatural Luck",
    description: `When the psyker uses a Divination psychic power on an ally without an Unnatural Luck effect, that ally gains Unnatural Luck. Unnatural Luck: when the ally suffers a critical hit, it becomes a normal hit instead and the Unnatural Luck effect is removed.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },

  {
    name: "Psyker - Pyromancer",
    description: `The target suffers (1 + WP + 6 x psy rating) to (2 x WP bonus + 10 x psy rating) damage and gains the Warp Burn effect. This attack has (5 × psyker’s psy rating)% armour penetration. Warp Burn: 3 + WP + 3 x PSY rating.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Blazing Inferno",
    description: `The psyker's critical hit chance increases by +1% until the end of combat every time the psyker deals damage by any means.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Backdraft",
    description: `Whenever a psychic power used by the psyker deals damage, a random enemy within 2 cells from the initial target suffers half of this damage. That damage does not trigger this talent again.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Body of Flames",
    description: `The psyker gains +(8 x psy rating)% additional armour against fire damage and half this amount as additional armour against energy damage from las, melta, and plasma weapons.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Relentless Blaze",
    description: `When the psyker is burning, the psyker's psy rating is increased by +1, and the psyker's resolve is increased by 2. Damage from fire no longer reduces the psyker's momentum.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Burning Blood",
    description: `When the psyker uses a psychic power, all enemies adjacent to the psyker suffer (4 x psy rating) direct damage. The same also happens when the psyker suffers damage from burning, bleeding, or melee attacks.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Fire Within",
    description: `Every time the psyker kills or scores a critical hit against 8 creatures in one combat, the psyker's next attack (including attacking psychic powers) will cost 0 AP and have no cooldown.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },

  {
    name: "Melting Armour",
    description: `Every time an enemy suffers damage from the psyker, that enemy's armour is reduced by -5%. If the enemy's armour is already 0, this enemy's deflection is reduced by -1 instead. (May be buggy and not always apply armour strip).`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Sparks of the Greater Flame",
    description: `All damage-over-time effects applied by the psyker gain additional % based on psy rating and other talents (complex stacking rules). Critical hit chance is increased by all bonuses to critical hit chance.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Psyker - Sanctic",
    description: `All allies in a circle with a 5-cell radius gain (1 + psy rating) resolve until the end of combat. Every additional stack of this effect increases the resolve bonus by +2.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },

  {
    name: "Destined",
    description: `The psyker's armour increases by +5%. This bonus increases by +5% at the start of every turn of combat except the first.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Edge of Dawn",
    description: `Enemies adjacent to the psyker suffer +10% more damage.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Eternal Glory",
    description: `The first time that momentum reaches 200 during the psyker's turn, the psyker gains +5 to all characteristics, +1 to resolve, +1 to deflection, and +1 to all damage that the psyker deals until the end of combat.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Hymns of Hatred",
    description: `Critical hits scored by anyone within the psyker's line of sight (including the psyker themselves) increase the psyker's critical damage by +1% until the end of combat. Stacks.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Psalms of Heroes",
    description: `The psyker's psy rating is increased by +1 until the end of combat every time an ally uses a heroic act.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Sanctified Slayer",
    description: `The psyker's critical hit chance is increased by +Resolve%`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },

  {
    name: "Psyker - Telepath",
    description: `Deals 4 + (psyker’s WP bonus × (1 + psy rating)) to (4 + psyker's WP bonus × (1 + psy rating)) damage to the target.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Aftershock",
    description: `Every time the psyker deals mental damage from any source other than Aftershock, the target suffers half as much mental damage at the end of its next turn.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Mental Breach",
    description: `Enemies that have taken damage from the psyker at least once suffer a -20 penalty to all resistance tests against the psyker until the end of combat.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Mind Siege",
    description: `Enemies that have failed a Willpower resistance test against any of the psyker's psychic powers will suffer an additional +(4 x psy rating) mental damage every time they suffer mental damage until the end of combat.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Mind Thief",
    description: `Any time an enemy becomes a target of any particular psyker ability for the first time, this enemy suffers a -5 penalty to their Intelligence and Perception, and the psyker's Intelligence and Perception increase by +2 until the end of combat.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Pain Channelling",
    description: `Whenever the psyker kills an enemy with a psychic power dealing more damage than wounds of the target, the excess damage will be dealt to the enemy closest to the target.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Visions of Doom",
    description: `Enemies that become targets of the psyker's psychic powers gain a stacking -5% penalty to their dodge and parry until the end of combat.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Warp Minds",
    description: `After every sixth use of a psychic power by the psyker, all enemies gain a stacking -5 penalty to all characteristics until the end of combat.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Weak Hearts",
    description: `Enemies currently inflicted with blinded, stunned, immobilised, or prone effects by the psyker suffer +10% more damage.`,
    groupId: 7,
    talentTypeId: 2,
    createdAt: new Date(),
  },

]
