export const soldier = [
  {
    name: "Run and Gun",
    description: `The Soldier gains +(2 + AGI bonus / 2) MP. Their next attack costs -1 AP less and does not count toward the attack limit per turn.
Until the end of the next turn, the Soldier becomes winded. While winded, the Soldier suffers a -10 penalty to Skill and cannot use Run and Gun.`,
    groupId: 32,
    talentTypeId: 1,
    createdAt: new Date(),
  },

  {
    name: "Controlled Shot",
    description: `The Soldier gives a sign that they are about to open fire. The Soldier and their allies will automatically dodge the Soldier's next attack.`,
    groupId: 32,
    talentTypeId: 1,
    createdAt: new Date(),
  },
  {
    name: "Dash",
    description: `The Soldier immediately dashes in the selected direction, spending all their Movement points. Does not provoke attacks of opportunity. Allows the Soldier to dash through allies and enemies but not through obstacles.
Can only be used once per round.`,
    groupId: 32,
    talentTypeId: 1,
    createdAt: new Date(),
  },
  {
    name: "Concentrated Fire",
    description: `	The next ranged area attack made by the Soldier deals +((50 + 10 x BS bonus) / number of enemies in the area of effect)% damage and has an additional +(10 + 2 x BS bonus)% dodge reduction.`,
    groupId: 32,
    talentTypeId: 1,
    createdAt: new Date(),
  },
  {
    name: "Entrench",
    description: `The Soldier immediately spends all their AP and MP and gains a +30% bonus to cover efficiency.
The next time the Soldier uses Run and Gun, they gain back all spent AP and MP plus 1 additional AP. It also resets the 7 cooldown of all other Soldier's abilities except for Run and Gun.`,
    groupId: 32,
    talentTypeId: 1,
    createdAt: new Date(),
  },
  {
    name: "Rapid Fire",
    description: `The Soldier's next burst attacks will have its rate of fire doubled but deal -25% less damage. All the shots will follow random trajectories.
Only works with weapons capable of burst fire.`,
    groupId: 32,
    talentTypeId: 1,
    createdAt: new Date(),
  },

  {
    name: "Soldier",
    description: ``,
    groupId: 32,
    talentTypeId: 5,
    createdAt: new Date(),
  },
  {
    name: "Soldier I",
    description: ``,
    groupId: 32,
    talentTypeId: 5,
    createdAt: new Date(),
  },
  {
    name: "Soldier II",
    description: ``,
    groupId: 32,
    talentTypeId: 5,
    createdAt: new Date(),
  },
  {
    name: "Soldier III",
    description: ``,
    groupId: 32,
    talentTypeId: 5,
    createdAt: new Date(),
  },
  {
    name: "Soldier IV",
    description: ``,
    groupId: 32,
    talentTypeId: 5,
    createdAt: new Date(),
  },

  {
    name: "Camaraderie",
    description: `For each adjacent ally, the Soldier deals +(5 + BS bonus)% more damage to enemies.`,
    groupId: 32,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Exploit Surroundings",
    description: `Cover efficiency is increased by +10% for full cover and +20% for half cover.`,
    groupId: 32,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Fired Up",
    description: `Whenever the Soldier deals damage, their critical damage is increased by +1% until the end of combat.`,
    groupId: 32,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Rack and Ruin",
    description: `After the Soldier deals damage to 3 different enemies, the Soldier gains +(10 + 2 x BS bonus)% more damage for their next attack in the current combat.`,
    groupId: 32,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Rapid Reload",
    description: `Reloading costs -2 AP less (minimum 1). The first reload in a combat does not cost AP.`,
    groupId: 32,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Unpredictable",
    description: `The Soldier gains +(3 + AGI bonus)% critical hit chance. This bonus is doubled against enemies from which the Soldier is protected by cover at the moment of the attack.`,
    groupId: 32,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Alacrity",
    description: `Each shot fired by the Soldier grants them +1 Agility until the end of their next turn.`,
    groupId: 32,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Combat Medicae",
    description: `Healing an ally with a medikit in combat restores additional wounds equal to (Medicae / 10). Using medikits costs -1 AP less.`,
    groupId: 32,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Demolition Engineer",
    description: `The Soldier's Demolition instead of Intelligence is used to determine additional damage dealt with ranged area attacks. Deals 5% more damage for every 10 points in Demolition (instead of 5% for each 10 points of Intelligence).`,
    groupId: 32,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Enough Bullets for everyone",
    description: `The Soldier's second attack action in a turn deals +(5 + 2 x AGI bonus)% more damage to enemies that have not suffered damage from the Soldier during this turn.`,
    groupId: 32,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Forewarning",
    description: `While the Soldier has an ally adjacent to them, Controlled Shot costs -1 AP less to use.`,
    groupId: 32,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Fortress",
    description: `While the Soldier has full cover against an enemy, the Soldier gains +10% damage against that enemy, and the enemy's attacks deal -20% less damage against the Soldier and their cover if the cover is present at the moment when the shot is fired (even if the cover is destroyed by the shot).`,
    groupId: 32,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Integrity",
    description: `While at full wounds, the Soldier has +10 Ballistic Skill and +2 MP.`,
    groupId: 32,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Muzzle Velocity",
    description: `The first hit of each burst attack deals additional damage equal to the weapon's current rate of fire.`,
    groupId: 32,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "On the double",
    description: `The next use of Run and Gun, when used after Entrench, grants an additional +AGI bonus movement points.`,
    groupId: 32,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Point-blank",
    description: `All of the Soldier's area attacks gain +(5 + 3 x BS bonus)% armour penetration and ignore (BS bonus / 2) deflection when used against enemies in a 3-cell radius around the Soldier.`,
    groupId: 32,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Second skin",
    description: `The Soldier's medium armour does not reduce dodge.`,
    groupId: 32,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Swift Slaughter",
    description: `Revel in Slaughter can be used after 2 kills instead of 3.`,
    groupId: 32,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Tactical disengage",
    description: `Dash does not end the Soldier's movement for the turn. Enemies adjacent to the starting point of Dash will consider the Soldier their lowest priority target during their next turn.`,
    groupId: 32,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Tenderise",
    description: `Enemies damaged by the Soldier's area attacks suffer +(1 + BS bonus / 2) damage from the next attack that hits them.`,
    groupId: 32,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Trace the trajectory",
    description: `Whenever the Soldier successfully dodges or uses cover against an enemy's attack, they gain a guaranteed critical hit against that enemy.`,
    groupId: 32,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Unfaltering Fire",
    description: `Rapid Fire no longer reduces damage.`,
    groupId: 32,
    talentTypeId: 2,
    createdAt: new Date(),
  },

]
