export const vanguard = [
  {
    name: "Enduring Shield",
    description: `While the Vanguard has at least 1 temporary wound, they gain +(5 + TGH Bonus)% parry and armour.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Formidable Distraction",
    description: `All enemies in a 2-cell radius around the Vanguard suffer a -(5 + FEL bonus)% penalty to dodge against all attacks except the Vanguard's. If any of these enemies consider the Vanguard a priority target, those enemies suffer a -(5 + 2 x FEL bonus)% penalty to dodge instead.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Renitent Beacon",
    description: `Each Stack of unyielding beacon additionally increases armour and parry by +1%.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Resilient Beacon",
    description: `Critical hits deal -(15 + 2 x TGH bonus)% less damage to the Vanguard.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Selfless Resilience",
    description: `Allies affected by any of the Vanguard's abilities gain +(2 X Vanguard's FEL bonus)% armour for 1 round. Does not stack.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Taunting Defence",
    description: `The Vanguard gains +(5 + 2 x TGH bonus)% parry against enemies that consider the Vanguard a priority target.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Taunting Opportunity",
    description: `Whenever the Vanguard hits an enemy with an attack of opportunity, that enemy must make a Willpower resistance test. On a failed test, the Vanguard becomes this enemy's priority target until the end of the Vanguard's next turn.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Beacon of Might",
    description: `At the start of the Vanguard's turn, before their temporary wounds are lost, the Vanguard gains +number of temporary wounds Strength for 1 round.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Centre of Attention",
    description: `For each enemy that considers the Vanguard a priority target, the Vanguard's armour is increased by +5%.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Counter-Attack Stance",
    description: `Defensive Stance now has a -10 penalty to Weapon Skill for attacks of opportunity granted by this ability instead of -20. These attacks of opportunity deal an additional +TGH bonus damage.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Covering Bulwark",
    description: `While Bulwark is active, the Vanguard counts as full cover for their allies and grants the adjacent allies +(stacks of unyielding beacon / 2) damage deflection against ranged attacks.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Defensive Comrade",
    description: `While the Vanguard has at least one ally in a 2-cell radius, the Vanguard gains +(3 x Vanguard's TGH bonus)% parry.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Offensive Follow",
    description: `Whenever an ally uses Following!, that ally gains +(5 + 2 x Vanguard's FEL bonus)% more damage against all enemies in a 2-cell radius around the Vanguard for 1 round.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "On Your Feet!",
    description: `The next attack made by an ally under the effect of Forced Distraction additionally grants +3 MP to that ally.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Overwhelming Provocation",
    description: `If the target of Provocation is hit by at least one attack of opportunity caused by Provocation, the target gains +1 stack of fatigued until the end of combat. Fatigued: the target suffers a -10 penalty to Strength, Toughness, and Agility for each stack of fatigued. MP are reduced by -1 for each stack.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Protective Word",
    description: `All allies affected by the Vanguard's abilities (but not the Vanguard themselves) are -(5 + Vanguard's FEL bonus)% less likely to suffer a critical hit.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Punish The Imprudent",
    description: `Once per round, whenever an enemy that considers the Vanguard a priority target enters a cell adjacent to the Vanguard, that enemy provokes an attack of opportunity.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Unflinching",
    description: `Whenever an attack made by an ally hits the Vanguard for the first time in a round, that attack deals no damage to the Vanguard. If this attack is a burst attack, this applies to each successful hit in the burst.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Unyielding Resolve",
    description: `While at maximum stacks of unyielding beacon, the Vanguard gains +7 resolve.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Wall of Ferrocrete",
    description: `Wall of Rockcrete now grants +TGH bonus temporary wounds to allies.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Words of Endurance",
    description: `Whenever the Vanguard's ally in a 2-cell radius around them is hit, the Vanguard grants that ally +FEL bonus temporary Wounds. Once per round for each ally.`,
    groupId: 36,
    talentTypeId: 2,
    createdAt: new Date(),
  },
]
