export const warrior = [
  {
    name: "Endure",
    description: `Until the warriors next turn, they gain (TGH \\2) Deflection and (10 + level \\6) temporary Wounds`,
    groupId: 29,
    talentTypeId: 1,
    createdAt: new Date(),
  },
  {
    name: "Reckless Strike",
    description: `The warrior's next melee attack agains +(5 x STR)% armour penetration and (2x Strength) damage and ignores (3x WS)% of the target's parry. Every enemy who survives an attack enhanced by this ability will attawck the warrior in return, including creatures with ranged weapons.`,
    groupId: 29,
    talentTypeId: 1,
    createdAt: new Date(),
  },
  {
    name: "Sworn Enemy",
    description: `The Warrior marks a target, gaining +(10 + 2 x TGH bonus)% armour and +(2 + STR bonus) damage on melee attacks against that target.
If the target attacks the Warrior during this round, the Warrior gains +1 AP (once per round).`,
    groupId: 29,
    talentTypeId: 1,
    createdAt: new Date(),
  },
  {
    name: "Break Through",
    description: ` `,
    groupId: 29,
    talentTypeId: 1,
    createdAt: new Date(),
  },
  {
    name: "Forceful Strike",
    description: `The Warrior gathers all their strength for a crushing strike. Their next melee attack pushes the enemy away. The distance of that push is equal to (1 + Strength bonus / 2) cells.`,
    groupId: 29,
    talentTypeId: 1,
    createdAt: new Date(),
  },
  {
    name: "Taunting Scream",
    description: `The Warrior screams at their enemies to draw their attention and becomes a priority target of any enemy who fails a Willpower resistance test.`,
    groupId: 29,
    talentTypeId: 1,
    createdAt: new Date(),
  },

  {
    name: "Daring Breach",
    description: ``,
    groupId: 29,
    talentTypeId: 5,
    createdAt: new Date(),
  },

  {
    name: "Daring Breach I",
    description: ``,
    groupId: 29,
    talentTypeId: 5,
    createdAt: new Date(),
  },

  {
    name: "Daring Breach II",
    description: ``,
    groupId: 29,
    talentTypeId: 5,
    createdAt: new Date(),
  },

  {
    name: "Daring Breach III",
    description: ``,
    groupId: 29,
    talentTypeId: 5,
    createdAt: new Date(),
  },

  {
    name: "Daring Breach IV",
    description: ``,
    groupId: 29,
    talentTypeId: 5,
    createdAt: new Date(),
  },

  {
    name: "Contempt",
    description: `Whenever an enemy attacks the Warrior, the Warrior's next melee attack against that enemy deals an additional +TGH bonus damage. Does not stack, but it can be reactivated after another attack made by either the same enemy or a different one.`,
    groupId: 29,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Desolation",
    description: `The Warrior deals an additional +AGI bonus damage to enemies that have no allies in adjacent cells.`,
    groupId: 29,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Easy Target",
    description: `The Warrior's critical damage is increased by +(10 + 2 × STR bonus)% against enemies not armed with a melee weapon.`,
    groupId: 29,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Enrage",
    description: `If the Warrior has less than 50% wounds, they gain +(5 + (TGH bonus + AGI bonus))% critical hit chance.`,
    groupId: 29,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Epicentre of Slaughter",
    description: `Whenever the Warrior is attacked, they gain +1 stack of Epicentre of Slaughter until the end of combat. At the start of their turn, the Warrior gains +1 temporary wound for each stack. These temporary wounds cannot exceed the Warrior's TGH bonus.`,
    groupId: 29,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Thick Skin",
    description: `The Warrior gains +1 damage deflection. Their parry chance is increased by +25% of the Warrior's total armour.`,
    groupId: 29,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Blade Flurry",
    description: `Each use of Slash increases the damage dealt by Slash by +1 until the end of combat.`,
    groupId: 29,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Cautious Disengage",
    description: `Attacks of opportunity deal -(10 + 3 x WS bonus)% less damage to the Warrior. Movement within range of attacks of opportunity costs -1 MP less.`,
    groupId: 29,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Clenched Teeth",
    description: `The Warrior gains +TGH bonus damage deflection against the first attack made by every enemy this combat.`,
    groupId: 29,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Crowd Kill",
    description: `Area attacks deal an additional +(1 + STR bonus / 2) damage for each enemy in the area of effect.`,
    groupId: 29,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Defensive Manoeuvres",
    description: `When the Warrior takes damage, they gain +(5 + 2 x AGI bonus)% dodge. Stacks up to 3 times and resets after a successful dodge.`,
    groupId: 29,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Defensive Stance",
    description: `If the Warrior has not attacked this turn, they gain +(10 + 2 x TGH bonus)% armour. Charge and Slash do not affect this bonus.`,
    groupId: 29,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Disarm",
    description: `When the Warrior uses a single-shot or melee attack against a target, the Warrior gains +(5 + 2 x TGH bonus)% armour against attacks made by that target for 1 round.`,
    groupId: 29,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Field Medic",
    description: `Allows the Fighter to use Medikits without Medicae Skill. The Fighter also regains additional Wounds equal to their TGH Bonus whenever the Medikit is used on them.`,
    groupId: 29,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Hardened Scars",
    description: `Whenever the Warrior is hit while under the Endure effect, their damage deflection is increased by +1 until the Warrior's next turn.`,
    groupId: 29,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Impetus",
    description: `The damage dealt by Charge is increased by +(TGH bonus + STR bonus) when the ability is used from a distance of 5 or more cells.`,
    groupId: 29,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Interception",
    description: `When the Warrior parries an attack, their next Warrior archetype ability costs -1 AP less.`,
    groupId: 29,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Invigorating Hatred",
    description: `When the Warrior ends their turn near an enemy affected by the Sworn Enemy ability, the Warrior gains +(2 + TGH bonus) temporary wounds.`,
    groupId: 29,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Living Shield",
    description: `Enemies suffer a -10% penalty to their hit chance with ranged attacks (including area attacks) against the Warrior for every enemy in a 1-cell radius around the Warrior. Stacks up to 3 times.`,
    groupId: 29,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Open Engagement",
    description: `If there are no enemies adjacent to the Warrior at the start of the turn, the Warrior's damage is increased by +(2 x STR bonus) for one melee attack.`,
    groupId: 29,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Opening Strike",
    description: `Charge and Push increase the damage of ranged attacks made against affected enemies by +(5 + WS bonus)% until the end of combat. Does not stack.`,
    groupId: 29,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Ramming Speed",
    description: `Increases Charge distance by +3 cells.`,
    groupId: 29,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Reckless Fury",
    description: `Whenever the Warrior hits with Reckless Strike, this attack scores a guaranteed critical hit.`,
    groupId: 29,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Rigorous Training",
    description: `The Warrior becomes incredibly deft. Charge and Slash do not end the Warrior's movement and grant +(10 + AGI bonus)% dodge for 1 round after use.`,
    groupId: 29,
    talentTypeId: 2,
    createdAt: new Date(),
  },
  {
    name: "Shearing Strikes",
    description: `When the Warrior uses Slash with two melee weapons equipped, the Warrior deals damage from both weapons. (Currently bugged and does not work with Rigorous Training).`,
    groupId: 29,
    talentTypeId: 2,
    createdAt: new Date(),
  },
]
